import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const exists=p=>fs.existsSync(p);
const failures=[];
function check(ok,msg){if(!ok)failures.push(msg)}
const index=read('index.html');
const bridge=read('src/puter.ts');
const academicAI=read('src/academic-ai.ts');
const app=read('src/ScholarApp.tsx');
const parser=read('src/parser.ts');
const academic=exists('src/AcademicHub.tsx')?read('src/AcademicHub.tsx'):'';
const lecture=exists('src/LectureStudio.tsx')?read('src/LectureStudio.tsx'):'';
const seminar=exists('src/SeminarStudio.tsx')?read('src/SeminarStudio.tsx'):'';
const exam=exists('src/ExamDNAStudio.tsx')?read('src/ExamDNAStudio.tsx'):'';
const feed=exists('src/SmartFeed.tsx')?read('src/SmartFeed.tsx'):'';
const day=exists('src/ScholarDay.tsx')?read('src/ScholarDay.tsx'):'';

check(!/puter\.com|js\.puter|window\.puter/i.test(index+bridge+academicAI),'Third-party Puter login/runtime is still present');
check(bridge.includes('scholarmcp-core-75hnna.v2.appdeploy.ai'),'ScholarMCP internal cloud core is missing');
check(bridge.includes("corePost('ocr'")&&bridge.includes('ocrSource'),'Internal OCR bridge is missing');
check(bridge.includes("corePost('transcribe'")&&bridge.includes('speechToText'),'Internal lecture transcription bridge is missing');
check(bridge.includes('speechSynthesis'),'In-platform text-to-speech fallback is missing');
check(!bridge.includes("from './local-ai'"),'AI bridge still imports the on-device LLM');
check(!bridge.includes("from './local-ocr'"),'AI bridge still imports the on-device OCR');
check(parser.includes("ext==='pdf'")&&parser.includes('ocrSource'),'PDF + OCR ingestion path missing');
check(app.includes("view==='today'"),'Today route missing');
check(app.includes("view==='courses'"),'Courses route missing');
check(app.includes("view==='study'"),'Study route missing');
check(app.includes("view==='assignments'"),'Assignments route missing');
check(app.includes("view==='academic'"),'Academic OS route missing');
check(app.includes("view==='research'"),'Research route missing');
check(app.includes('CourseChat'),'Source-grounded course chat missing');
check(app.includes('QuizModal'),'Quiz UI missing');
check(app.includes('FlashcardsModal'),'Flashcard review UI missing');
check(app.includes('LectureStudio'),'Lecture Intelligence is not wired into Course Brain');
check(app.includes('AcademicHub'),'Academic Hub is not wired into navigation');
check(app.includes('ScholarDay'),'Scholar Day is not wired into Today');
check(academic.includes('SyllabusMagic'),'Syllabus Magic missing');
check(academic.includes('GradePlanner'),'Grade planner missing');
check(academic.includes('SeminarStudio'),'Seminar Studio missing from Academic Hub');
check(academic.includes('ExamDNAStudio'),'Exam DNA missing from Academic Hub');
check(academic.includes('SmartFeed'),'Smart Feed missing from Academic Hub');
check(lecture.includes('speechToText')&&lecture.includes('MediaRecorder'),'Lecture record/transcribe path incomplete');
check(seminar.includes('exportPptx')&&seminar.includes('buildSeminarRehearsal'),'Seminar export/rehearsal path incomplete');
check(exam.includes('analyzeExamDNA'),'Exam DNA analysis path incomplete');
check(feed.includes('reviewFSRS'),'Smart Feed is not tied to spaced repetition');
check(day.includes('riskScore')&&day.includes('dueDate'),'Scholar Day is not adaptive to risk/reviews');

if(failures.length){console.error('\nScholarMCP quality gate FAILED:\n- '+failures.join('\n- '));process.exit(1)}
console.log('ScholarMCP quality gate passed: no third-party login flow; internal cloud core, ingestion, Course Brain, lecture, Academic OS, seminar, Exam DNA, Smart Feed and Scholar Day are wired.');
