import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const exists=p=>fs.existsSync(p);
const failures=[];
function check(ok,msg){if(!ok)failures.push(msg)}
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(`${dir}/${x.name}`):[`${dir}/${x.name}`])}
const srcText=walk('src').filter(p=>/\.(ts|tsx|js|jsx)$/.test(p)).map(read).join('\n');
const index=read('index.html');
const bridge=read('src/puter.ts');
const localAI=read('src/local-ai.ts');
const localOCR=read('src/local-ocr.ts');
const localSpeech=read('src/local-speech.ts');
const app=read('src/ScholarApp.tsx');
const parser=read('src/parser.ts');
const academic=exists('src/AcademicHub.tsx')?read('src/AcademicHub.tsx'):'';
const lecture=exists('src/LectureStudio.tsx')?read('src/LectureStudio.tsx'):'';
const seminar=exists('src/SeminarStudio.tsx')?read('src/SeminarStudio.tsx'):'';
const exam=exists('src/ExamDNAStudio.tsx')?read('src/ExamDNAStudio.tsx'):'';
const feed=exists('src/SmartFeed.tsx')?read('src/SmartFeed.tsx'):'';
const day=exists('src/ScholarDay.tsx')?read('src/ScholarDay.tsx'):'';
const project=exists('src/AcademicProjectStudio.tsx')?read('src/AcademicProjectStudio.tsx'):'';
const video=exists('src/StudyVideoStudio.tsx')?read('src/StudyVideoStudio.tsx'):'';
const bag=exists('src/academic-bag.ts')?read('src/academic-bag.ts'):'';

check(!/puter\.com|js\.puter|window\.puter|appdeploy\.ai|scholarmcp-core/i.test(index+srcText),'External AI runtime/login dependency is still present');
check(!/Scholar Core|معالجة سحابية|على السحابة|تتم سحابيًا|CLOUD-FIRST/i.test(app+lecture+academic),'Stale cloud-runtime claims are still visible in the product UI');
check(app.includes('AI محلي • على جهازك'),'Topbar does not disclose the local engine truth');
check(app.includes('Qwen محلي')&&app.includes('Granite + TrOCR')&&app.includes('Whisper محلي'),'Settings do not describe the real local engines');
check(bridge.includes("from './local-ai'")&&bridge.includes("from './local-ocr'")&&bridge.includes("from './local-speech'"),'Scholar engine bridge is not fully local');
check(localAI.includes('Qwen3-0.6B-ONNX')&&localAI.includes("import('@huggingface/transformers')"),'Local Qwen engine is missing');
check(localAI.includes("case'custom'")&&localAI.includes('customTask'),'Generic academic local task path is missing');
check(localOCR.includes('granite-docling-258M-ONNX')&&localOCR.includes('trocr-small-handwritten'),'Local document/handwriting OCR is incomplete');
check(localSpeech.includes('whisper-tiny')&&localSpeech.includes('automatic-speech-recognition'),'Local lecture transcription engine is missing');
check(bridge.includes('fallbackCustom'),'No-dead-button academic fallback is missing');
check(bridge.includes('speechSynthesis'),'In-platform text-to-speech is missing');
check(parser.includes("ext==='pdf'")&&parser.includes('ocrSource'),'PDF + OCR ingestion path missing');
check(app.includes("view==='today'"),'Today route missing');
check(app.includes("view==='courses'"),'Courses route missing');
check(app.includes("view==='study'"),'Study route missing');
check(app.includes("view==='assignments'"),'Assignments route missing');
check(app.includes("view==='academic'"),'Academic OS route missing');
check(app.includes("view==='research'"),'Research route missing');
check(app.includes('CourseChat'),'Source-grounded course chat missing');
check(app.includes('QuizModal'),'Quiz UI missing');
check(app.includes('FlashcardsModal'),'Flashcard review UI missing');
check(app.includes('LectureStudio'),'Lecture Intelligence is not wired into Course Brain');
check(app.includes('AcademicHub'),'Academic Hub is not wired into navigation');
check(app.includes('ScholarDay'),'Scholar Day is not wired into Today');
check(academic.includes('SyllabusMagic'),'Syllabus Magic missing');
check(academic.includes('GradePlanner'),'Grade planner missing');
check(academic.includes('SeminarStudio'),'Seminar Studio missing from Academic Hub');
check(academic.includes('ExamDNAStudio'),'Exam DNA missing from Academic Hub');
check(academic.includes('SmartFeed'),'Smart Feed missing from Academic Hub');
check(academic.includes('AcademicProjectStudio'),'Academic Project Studio missing from Academic Hub');
check(academic.includes('StudyVideoStudio'),'AI Study Video missing from Academic Hub');
check(lecture.includes('speechToText')&&lecture.includes('MediaRecorder'),'Lecture record/transcribe path incomplete');
check(lecture.includes('45_000')&&lecture.includes('recordedParts'),'Long lecture safe segmentation is missing');
check(seminar.includes('exportPptx')&&seminar.includes('buildSeminarRehearsal'),'Seminar export/rehearsal path incomplete');
check(exam.includes('analyzeExamDNA'),'Exam DNA analysis path incomplete');
check(feed.includes('reviewFSRS'),'Smart Feed is not tied to spaced repetition');
check(day.includes('riskScore')&&day.includes('dueDate'),'Scholar Day is not adaptive to risk/reviews');
check(project.includes('citationHealth')&&project.includes('unsupportedClaims'),'Academic project citation/claim audit is missing');
check(project.includes('exportAcademicBag')&&project.includes('exportPptx')&&project.includes('exportDocx'),'Academic project export pipeline is incomplete');
check(video.includes('customTask')&&video.includes('MediaRecorder')&&video.includes('captureStream'),'In-platform AI study video pipeline is incomplete');
check(bag.includes('JSZip')&&bag.includes('flashcards.tsv')&&bag.includes('manifest.json'),'Full academic bag export is incomplete');

if(failures.length){console.error('\nScholarMCP quality gate FAILED:\n- '+failures.join('\n- '));process.exit(1)}
console.log('ScholarMCP quality gate passed: repository-local Qwen, OCR, Whisper, local fallback, Course Brain, long lectures, Academic Project, AI video, academic bag, seminar, Exam DNA, Smart Feed and Scholar Day are wired with truthful local-engine UI and no external AI login/runtime.');
