import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const exists=p=>fs.existsSync(p);
const failures=[];
function check(ok,msg){if(!ok)failures.push(msg)}
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(`${dir}/${x.name}`):[`${dir}/${x.name}`])}
const srcText=walk('src').filter(p=>/\.(ts|tsx|js|jsx)$/.test(p)).map(read).join('\n');
const index=read('index.html');
const main=read('src/main.tsx');
const engine=read('src/scholar-engine.ts');
const localAI=read('src/local-ai.ts');
const localOCR=read('src/local-ocr.ts');
const localSpeech=read('src/local-speech.ts');
const app=read('src/ScholarApp.tsx');
const parser=read('src/parser.ts');
const academic=exists('src/AcademicHub.tsx')?read('src/AcademicHub.tsx'):'';
const lecture=exists('src/LectureStudio.tsx')?read('src/LectureStudio.tsx'):'';
const seminar=exists('src/SeminarStudio.tsx')?read('src/SeminarStudio.tsx'):'';
const exam=exists('src/ExamDNAStudio.tsx')?read('src/ExamDNAStudio.tsx'):'';
const feed=exists('src/SmartFeed.tsx')?read('src/SmartFeed.tsx'):'';
const day=exists('src/ScholarDay.tsx')?read('src/ScholarDay.tsx'):'';
const project=exists('src/AcademicProjectStudio.tsx')?read('src/AcademicProjectStudio.tsx'):'';
const video=exists('src/StudyVideoStudio.tsx')?read('src/StudyVideoStudio.tsx'):'';
const bag=exists('src/academic-bag.ts')?read('src/academic-bag.ts'):'';
const studentTools=exists('src/StudentTools.tsx')?read('src/StudentTools.tsx'):'';
const researchLab=exists('src/ResearchWorkbench.tsx')?read('src/ResearchWorkbench.tsx'):'';
const focus=exists('src/FocusStudio.tsx')?read('src/FocusStudio.tsx'):'';
const manifest=exists('public/manifest.webmanifest')?read('public/manifest.webmanifest'):'';
const sw=exists('public/sw.js')?read('public/sw.js'):'';

check(!exists('src/puter.ts'),'Legacy Puter bridge file still exists');
check(!/puter\.com|js\.puter|window\.puter|appdeploy\.ai|scholarmcp-core|\.\/puter['"]/i.test(index+srcText),'External/legacy AI runtime dependency is still present');
check(!/Scholar Core|معالجة سحابية|على السحابة|تتم سحابيًا|CLOUD-FIRST/i.test(app+lecture+academic),'Stale cloud-runtime claims are still visible in the product UI');
check(app.includes('AI محلي • على جهازك'),'Topbar does not disclose the local engine truth');
check(app.includes('Qwen محلي')&&app.includes('Granite + TrOCR')&&app.includes('Whisper محلي'),'Settings do not describe the real local engines');
check(engine.includes("from './local-ai'")&&engine.includes("from './local-ocr'")&&engine.includes("from './local-speech'"),'Scholar engine bridge is not fully local');
check(engine.includes('fallbackCustom')&&engine.includes('speechSynthesis'),'Local fallback/TTS bridge is incomplete');
check(localAI.includes('Qwen3-0.6B-ONNX')&&localAI.includes("import('@huggingface/transformers')"),'Local Qwen engine is missing');
check(localAI.includes('glossaryLock')&&localAI.includes('Glossary Lock'),'Local translation Glossary Lock is missing');
check(localAI.includes("case'custom'")&&localAI.includes('customTask'),'Generic academic local task path is missing');
check(localOCR.includes('granite-docling-258M-ONNX')&&localOCR.includes('trocr-small-handwritten'),'Local document/handwriting OCR is incomplete');
check(localSpeech.includes('whisper-tiny')&&localSpeech.includes('automatic-speech-recognition'),'Local lecture transcription engine is missing');
check(parser.includes("ext==='pdf'")&&parser.includes('ocrSource'),'PDF + OCR ingestion path missing');
check(app.includes("view==='today'")&&app.includes("view==='courses'")&&app.includes("view==='study'")&&app.includes("view==='assignments'")&&app.includes("view==='academic'")&&app.includes("view==='research'"),'Core Student OS routes are incomplete');
check(app.includes('CourseChat')&&app.includes('QuizModal')&&app.includes('FlashcardsModal'),'Course Brain learning tools are incomplete');
check(app.includes('LectureStudio')&&app.includes('AcademicHub')&&app.includes('ScholarDay'),'Core adaptive Student OS wiring is incomplete');
check(academic.includes('SyllabusMagic')&&academic.includes('GradePlanner'),'Syllabus/grade planner missing');
check(academic.includes('SeminarStudio')&&academic.includes('ExamDNAStudio')&&academic.includes('SmartFeed'),'Seminar/Exam DNA/Smart Feed missing');
check(academic.includes('AcademicProjectStudio')&&academic.includes('StudyVideoStudio'),'Academic Project/AI video missing');
check(academic.includes('TranslationStudio')&&academic.includes('CoverageGuard')&&academic.includes('ExamSimulator'),'Translation/Coverage/Exam Simulator not wired into Academic Hub');
check(academic.includes('VoiceTutor')&&academic.includes('LearningGraph'),'Voice Tutor/Learning Graph not wired into Academic Hub');
check(academic.includes('ResearchWorkbench')&&academic.includes('FocusStudio'),'Research/Integrity Lab or Focus Mode not wired into Academic Hub');
check(studentTools.includes('glossaryLock')&&studentTools.includes('CoverageGuard')&&studentTools.includes('ExamSimulator')&&studentTools.includes('VoiceTutor')&&studentTools.includes('LearningGraph'),'Advanced Student Tools implementation is incomplete');
check(/Citation Builder/i.test(researchLab)&&/Claim Verification/i.test(researchLab)&&/Literature Review/i.test(researchLab)&&/Integrity Guard/i.test(researchLab),'Academic Research/Integrity workbench is incomplete');
check(focus.includes('FOCUS MODE')&&focus.includes('scholarmcp.focus.sessions.v1'),'Focus Mode persistence is missing');
check(lecture.includes('speechToText')&&lecture.includes('MediaRecorder')&&lecture.includes('45_000')&&lecture.includes('recordedParts'),'Long lecture record/transcribe path is incomplete');
check(seminar.includes('exportPptx')&&seminar.includes('buildSeminarRehearsal'),'Seminar export/rehearsal path incomplete');
check(exam.includes('analyzeExamDNA'),'Exam DNA analysis path incomplete');
check(feed.includes('reviewFSRS'),'Smart Feed is not tied to spaced repetition');
check(day.includes('riskScore')&&day.includes('dueDate'),'Scholar Day is not adaptive to risk/reviews');
check(project.includes('citationHealth')&&project.includes('unsupportedClaims')&&project.includes('exportAcademicBag'),'Academic project citation/claim/export pipeline is incomplete');
check(video.includes('customTask')&&video.includes('MediaRecorder')&&video.includes('captureStream'),'In-platform AI study video pipeline is incomplete');
check(bag.includes('JSZip')&&bag.includes('flashcards.tsv')&&bag.includes('manifest.json'),'Full academic bag export is incomplete');
check(index.includes('manifest.webmanifest')&&manifest.includes('"display": "standalone"'),'Installable PWA manifest is missing');
check(main.includes('serviceWorker.register')&&/scholarmcp-shell-v\d+/.test(sw),'Offline app-shell registration/cache is missing');

if(failures.length){console.error('\nScholarMCP quality gate FAILED:\n- '+failures.join('\n- '));process.exit(1)}
console.log('ScholarMCP quality gate passed: no Puter/AppDeploy runtime; local Qwen/OCR/Whisper, Glossary Lock, Coverage Guard, Exam Simulator, Voice Tutor, Learning Graph, Research/Integrity Lab, Focus Mode, PWA shell, Course Brain, long lectures, Academic Project, AI video, seminar, Exam DNA, Smart Feed and Scholar Day are wired.');
