import {useMemo,useState} from 'react';
import {BookOpen,CheckCircle2,Download,FileCheck2,FileText,LoaderCircle,Presentation,ShieldCheck,Sparkles,TriangleAlert} from 'lucide-react';
import {type AppState,LocalRepository,exportDocx,exportPptx,retrieve} from './lib';
import {customTask} from './puter';
import {exportAcademicBag} from './academic-bag';
import './academic-project.css';

const repo=new LocalRepository();
type Props={state:AppState;notify:(message:string)=>void};
type Section={heading:string;body:string;usedRefs:string[]};
type Audit={citationHealth:number;requirementsMatch:number;readiness:number;unsupportedClaims:Array<{claim:string;reason:string}>;requirements:Array<{text:string;status:'met'|'partial'|'missing'}>;notes:string[]};
type Project={title:string;abstract:string;sections:Section[];references:string[];audit:Audit};
const styles=['APA 7','MLA 9','Chicago','Harvard','Vancouver'];
const languages=['العربية','English','Türkçe','Français','Deutsch'];
function clamp(n:number){return Math.max(0,Math.min(100,Math.round(Number(n)||0)))}
function researchText(project:Project){return `${project.title}\n\nالملخص\n${project.abstract}\n\n${project.sections.map(s=>`${s.heading}\n${s.body}`).join('\n\n')}\n\nالمراجع\n${project.references.map((r,i)=>`${i+1}. ${r}`).join('\n')}`}
function sentences(text:string){return text.split(/(?<=[.!?؟])\s+/).map(x=>x.trim()).filter(Boolean)}
function printResearch(project:Project){const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='1px';frame.style.height='1px';frame.style.opacity='0';document.body.appendChild(frame);const doc=frame.contentDocument;if(!doc){frame.remove();return}doc.open();doc.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${project.title}</title><style>body{font-family:Arial,sans-serif;line-height:1.9;margin:40px;color:#111}h1{text-align:center}h2{margin-top:28px}p{white-space:pre-wrap}.refs{direction:ltr;text-align:left}@media print{body{margin:18mm}}</style></head><body><h1>${project.title}</h1><h2>الملخص</h2><p>${project.abstract}</p>${project.sections.map(s=>`<h2>${s.heading}</h2><p>${s.body}</p>`).join('')}<h2>المراجع</h2><ol class="refs">${project.references.map(r=>`<li>${r}</li>`).join('')}</ol></body></html>`);doc.close();setTimeout(()=>{frame.contentWindow?.focus();frame.contentWindow?.print();setTimeout(()=>frame.remove(),1200)},250)}

export default function AcademicProjectStudio({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [title,setTitle]=useState('');const [pages,setPages]=useState(8);const [slides,setSlides]=useState(12);const [citationStyle,setCitationStyle]=useState('APA 7');const [language,setLanguage]=useState('العربية');const [referenceCheck,setReferenceCheck]=useState(true);const [requirements,setRequirements]=useState('');const [busy,setBusy]=useState('');const [project,setProject]=useState<Project|null>(null);
 const course=state.courses.find(c=>c.id===courseId);const mats=useMemo(()=>state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim()),[state.materials,courseId]);const artifacts=state.artifacts.filter(a=>a.courseId===courseId);
 async function build(){if(!course||!mats.length){notify('اختَر مادة وارفع مصدرًا جاهزًا أولاً');return}setBusy('plan');setProject(null);try{
   const sourceIndex=mats.map(m=>`${m.name} — ${m.pages} صفحة`).join('\n');
   const plan:any=await customTask(`أنت مهندس بحث أكاديمي داخل ScholarMCP. أنشئ خطة بحث متوازنة لمشروع بعنوان «${title.trim()||course.name}». المطلوب تقريباً ${pages} صفحات، لغة الإخراج ${language}، نمط التوثيق ${citationStyle}. متطلبات الطالب:\n${requirements||'لا توجد متطلبات إضافية.'}\nأعد JSON: {"title":"...","abstractGoal":"...","sections":[{"heading":"...","goal":"..."}]}. اجعل عدد الأقسام بين 4 و8 ولا تضف مراجع من عندك.`,`قائمة المصادر المتاحة:\n${sourceIndex}`);
   const planned=Array.isArray(plan.sections)&&plan.sections.length?plan.sections.slice(0,8):[{heading:'المقدمة',goal:'تمهيد للمادة'},{heading:'المفاهيم الأساسية',goal:'شرح المفاهيم'},{heading:'المناقشة',goal:'تحليل المادة'},{heading:'الخاتمة',goal:'استنتاجات مدعومة'}];
   const targetWords=Math.max(260,Math.min(750,Math.round((pages*360)/planned.length)));const built:Section[]=[];
   for(let i=0;i<planned.length;i++){setBusy(`section:${i+1}/${planned.length}`);const p=planned[i];const hits=retrieve(mats,`${p.heading} ${p.goal}`,14);const ctx=hits.map(h=>`SOURCE ${h.material}\n[[PAGE ${h.page}]]\n${h.text}`).join('\n\n');const result:any=await customTask(`اكتب قسم بحث أكاديمي بعنوان «${p.heading}» وهدفه «${p.goal}». اكتب قرابة ${targetWords} كلمة بلغة ${language}. ممنوع إدخال معلومة غير موجودة في المصدر. وثّق الادعاءات داخل النص بمراجع قابلة للتتبع بصيغة (اسم الملف، ص N)، ولا تختلق اسم مؤلف أو سنة غير موجودة. نمط التوثيق النهائي المطلوب ${citationStyle}. أعد JSON: {"heading":"...","body":"...","usedRefs":["اسم الملف — ص N"]}.`,ctx);built.push({heading:String(result.heading||p.heading),body:String(result.body||result.text||''),usedRefs:Array.isArray(result.usedRefs)?result.usedRefs:[]})}
   setBusy('audit');const draft={title:String(plan.title||title.trim()||course.name),sections:built};const auditCtx=mats.flatMap(m=>retrieve([m],draft.title,5).map(h=>`SOURCE ${h.material}\n[[PAGE ${h.page}]]\n${h.text}`)).join('\n\n').slice(0,80000);const auditRaw:any=await customTask(`دقق البحث التالي تدقيقاً صارماً مقارنة بالمصدر. قيّم سلامة الاستشهادات، مطابقة المتطلبات، الجاهزية للتسليم، وحدد أي ادعاء غير مدعوم. لا تجامل. متطلبات الطالب: ${requirements||'لا توجد'}. نمط التوثيق ${citationStyle}. أعد JSON: {"citationHealth":0,"requirementsMatch":0,"readiness":0,"unsupportedClaims":[{"claim":"...","reason":"..."}],"requirements":[{"text":"...","status":"met|partial|missing"}],"notes":["..."]}.\nالبحث:\n${JSON.stringify(draft).slice(0,70000)}`,auditCtx);const audit:Audit={citationHealth:clamp(auditRaw.citationHealth),requirementsMatch:clamp(auditRaw.requirementsMatch),readiness:clamp(auditRaw.readiness),unsupportedClaims:Array.isArray(auditRaw.unsupportedClaims)?auditRaw.unsupportedClaims:[],requirements:Array.isArray(auditRaw.requirements)?auditRaw.requirements:[],notes:Array.isArray(auditRaw.notes)?auditRaw.notes:[]};
   const refSet=new Set<string>();for(const s of built)for(const r of s.usedRefs)if(r)refSet.add(r);const finalProject:Project={title:draft.title,abstract:String(plan.abstractGoal||built[0]?.body.slice(0,500)||''),sections:built,references:[...refSet],audit};setProject(finalProject);repo.addArtifact({courseId,type:'research-project',title:`مشروع أكاديمي — ${finalProject.title}`,truth:audit.unsupportedClaims.length?'inferred':'supported',coverage:audit.citationHealth,data:{...finalProject,settings:{pages,slides,citationStyle,language,referenceCheck,requirements}}});notify('اكتمل بناء البحث والتدقيق وحفظ المشروع داخل المادة')
 }catch(e){notify((e as Error).message)}finally{setBusy('')}}
 function makeSlides(){if(!project)return;const deck=project.sections.slice(0,Math.max(4,Math.min(slides,project.sections.length))).map(s=>({title:s.heading,bullets:sentences(s.body).slice(0,4),notes:`المراجع المستخدمة: ${s.usedRefs.join('، ')||'راجع المصدر'}`}));exportPptx({title:project.title,slides:deck})}
 async function bag(){try{const r=await exportAcademicBag(state,courseId);notify(`نزلت الحقيبة الأكاديمية — ${r.files} عنصر`)}catch(e){notify((e as Error).message)}}
 return <div className="academic-project"><div className="panel project-config"><div className="section-head"><div><span className="eyebrow">ACADEMIC PROJECT</span><h3>مساحة العمل الأكاديمية</h3><p>مصادر الطالب → بحث موثق → تدقيق الادعاءات → عرض → حقيبة تسليم.</p></div><BookOpen/></div><div className="project-fields"><label>المادة<select value={courseId} onChange={e=>{setCourseId(e.target.value);setProject(null)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>عنوان المشروع<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={course?.name||'عنوان البحث'}/></label><label>عدد الصفحات<input type="number" min="3" max="20" value={pages} onChange={e=>setPages(Number(e.target.value))}/></label><label>عدد الشرائح<input type="number" min="4" max="30" value={slides} onChange={e=>setSlides(Number(e.target.value))}/></label><label>نمط التوثيق<select value={citationStyle} onChange={e=>setCitationStyle(e.target.value)}>{styles.map(x=><option key={x}>{x}</option>)}</select></label><label>لغة الإخراج<select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x}>{x}</option>)}</select></label></div><label className="requirements">متطلبات الدكتور / التعليمات<textarea rows={4} value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="الصق التعليمات أو الـRubric هنا…"/></label><label className="reference-toggle"><input type="checkbox" checked={referenceCheck} onChange={e=>setReferenceCheck(e.target.checked)}/><span><ShieldCheck/> فحص المراجع والادعاءات قبل التسليم</span></label><button className="primary wide" disabled={!!busy||!mats.length} onClick={build}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>} {busy.startsWith('section:')?`أكتب القسم ${busy.split(':')[1]}`:busy==='audit'?'أدقق البحث…':busy?'أبني الخطة…':'ابنِ المشروع الأكاديمي'}</button><small>المصادر الجاهزة: {mats.length} • المخرجات السابقة: {artifacts.length}</small></div>
 {project&&<><div className="project-status"><Metric icon={ShieldCheck} label="سلامة الاستشهادات" value={project.audit.citationHealth}/><Metric icon={FileCheck2} label="مطابقة المتطلبات" value={project.audit.requirementsMatch}/><div className={`project-metric ${project.audit.unsupportedClaims.length?'danger':'good'}`}><TriangleAlert/><span>ادعاءات بلا مصدر</span><b>{project.audit.unsupportedClaims.length}</b></div><Metric icon={CheckCircle2} label="جاهزية التسليم" value={project.audit.readiness}/></div><div className="panel project-output"><div className="section-head"><div><h3>{project.title}</h3><p>نسخة قابلة للمراجعة قبل التصدير.</p></div><div className="export-inline"><button className="ghost" onClick={()=>exportDocx(project.title,researchText(project))}><FileText/> Word</button><button className="ghost" onClick={()=>printResearch(project)}><Download/> PDF</button><button className="ghost" onClick={makeSlides}><Presentation/> PowerPoint</button><button className="primary" onClick={bag}><Download/> الحقيبة الكاملة</button></div></div><div className="research-paper"><h4>الملخص</h4><p>{project.abstract}</p>{project.sections.map((s,i)=><section key={i}><h4>{s.heading}</h4><p>{s.body}</p>{s.usedRefs.length>0&&<small>{s.usedRefs.join(' • ')}</small>}</section>)}</div></div>{(project.audit.unsupportedClaims.length>0||project.audit.requirements.length>0)&&<div className="project-audit-grid"><div className="panel"><h4>الادعاءات التي تحتاج إصلاح</h4>{project.audit.unsupportedClaims.length?project.audit.unsupportedClaims.map((x,i)=><article className="audit-claim" key={i}><TriangleAlert/><div><b>{x.claim}</b><p>{x.reason}</p></div></article>):<p className="good-text">ماكو ادعاء واضح بلا دعم حسب الفحص الحالي.</p>}</div><div className="panel"><h4>مطابقة متطلبات التسليم</h4>{project.audit.requirements.map((x,i)=><div className={`requirement-row ${x.status}`} key={i}><span>{x.status==='met'?'✓':x.status==='partial'?'~':'!'}</span><p>{x.text}</p></div>)}{project.audit.notes.map((x,i)=><small key={i}>• {x}</small>)}</div></div>}</>}
 </div>
}
function Metric({icon:Icon,label,value}:{icon:typeof ShieldCheck;label:string;value:number}){return <div className={`project-metric ${value>=80?'good':value>=60?'warn':'danger'}`}><Icon/><span>{label}</span><b>{value}%</b><div><i style={{width:`${value}%`}}/></div></div>}
