import {useMemo,useRef,useState} from 'react';
import {BarChart3,BookOpen,CalendarDays,CheckCircle2,Clock,FileCheck2,FileQuestion,FileText,Flame,GitBranch,GraduationCap,Languages,LoaderCircle,Mic,Plus,Presentation,Save,Sparkles,Trash2,Upload,Video} from 'lucide-react';
import {type AppState,LocalRepository,parseFile} from './lib';
import {analyzeSyllabus} from './academic-ai';
import SeminarStudio from './SeminarStudio';
import ExamDNAStudio from './ExamDNAStudio';
import SmartFeed from './SmartFeed';
import AcademicProjectStudio from './AcademicProjectStudio';
import StudyVideoStudio from './StudyVideoStudio';
import {CoverageGuard,ExamSimulator,LearningGraph,TranslationStudio,VoiceTutor} from './StudentTools';
import './academic-hub.css';

type Props={state:AppState;notify:(message:string)=>void};
type GradeItem={id:string;name:string;weight:number;score:number|string};
type GradePlans=Record<string,{target:number;items:GradeItem[]}>;
type AcademicTab='project'|'syllabus'|'grades'|'seminar'|'exam'|'feed'|'video'|'translation'|'coverage'|'simulator'|'voice'|'graph';
const repo=new LocalRepository();
const GRADE_KEY='scholarmcp.grades.v1';
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function loadPlans():GradePlans{try{return JSON.parse(localStorage.getItem(GRADE_KEY)||'{}')}catch{return{}}}
function savePlans(v:GradePlans){localStorage.setItem(GRADE_KEY,JSON.stringify(v))}

export default function AcademicHub({state,notify}:Props){
 const [tab,setTab]=useState<AcademicTab>('project');
 return <section><div className="academic-head"><div><span className="eyebrow">ACADEMIC OS</span><h1>مركز الفصل الدراسي</h1><p>من أول ملف إلى بحث موثق، ترجمة، امتحان، صوت، فيديو، ومراجعة — بدون مغادرة ScholarMCP.</p></div><GraduationCap/></div><div className="tabs academic-tabs"><button className={tab==='project'?'active':''} onClick={()=>setTab('project')}><BookOpen/> مشروع أكاديمي</button><button className={tab==='translation'?'active':''} onClick={()=>setTab('translation')}><Languages/> الترجمة</button><button className={tab==='coverage'?'active':''} onClick={()=>setTab('coverage')}><FileCheck2/> Coverage Guard</button><button className={tab==='simulator'?'active':''} onClick={()=>setTab('simulator')}><Clock/> محاكي الفاينل</button><button className={tab==='voice'?'active':''} onClick={()=>setTab('voice')}><Mic/> المدرس الصوتي</button><button className={tab==='graph'?'active':''} onClick={()=>setTab('graph')}><GitBranch/> خريطة التعلم</button><button className={tab==='syllabus'?'active':''} onClick={()=>setTab('syllabus')}><FileText/> سيلابس ذكي</button><button className={tab==='grades'?'active':''} onClick={()=>setTab('grades')}><BarChart3/> الدرجات والهدف</button><button className={tab==='seminar'?'active':''} onClick={()=>setTab('seminar')}><Presentation/> سيمنار</button><button className={tab==='exam'?'active':''} onClick={()=>setTab('exam')}><FileQuestion/> بصمة الامتحان</button><button className={tab==='feed'?'active':''} onClick={()=>setTab('feed')}><Flame/> Smart Feed</button><button className={tab==='video'?'active':''} onClick={()=>setTab('video')}><Video/> فيديو AI</button></div>{tab==='project'&&<AcademicProjectStudio state={state} notify={notify}/>} {tab==='translation'&&<TranslationStudio state={state} notify={notify}/>} {tab==='coverage'&&<CoverageGuard state={state} notify={notify}/>} {tab==='simulator'&&<ExamSimulator state={state} notify={notify}/>} {tab==='voice'&&<VoiceTutor state={state} notify={notify}/>} {tab==='graph'&&<LearningGraph state={state}/>} {tab==='syllabus'&&<SyllabusMagic state={state} notify={notify}/>} {tab==='grades'&&<GradePlanner state={state} notify={notify}/>} {tab==='seminar'&&<SeminarStudio state={state} notify={notify}/>} {tab==='exam'&&<ExamDNAStudio state={state} notify={notify}/>} {tab==='feed'&&<SmartFeed state={state} notify={notify}/>} {tab==='video'&&<StudyVideoStudio state={state} notify={notify}/>}</section>
}

function SyllabusMagic({state,notify}:Props){const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [file,setFile]=useState<File|null>(null);const [data,setData]=useState<any>(null);async function run(f:File){setFile(f);setBusy(true);setData(null);try{const parsed=await parseFile(f);if(!parsed.text.trim())throw new Error(parsed.error||'السيلابس ما بي نص قابل للقراءة.');const d=await analyzeSyllabus(parsed.text);setData(d);notify('حللت السيلابس ورتبت المطلوبات')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}function apply(){if(!data)return;let course=state.courses.find(c=>c.name.trim().toLowerCase()===String(data.courseName||'').trim().toLowerCase());if(!course)course=repo.addCourse(String(data.courseName||file?.name.replace(/\.[^.]+$/,'')||'مادة جديدة'));for(const d of data.deadlines||[]){if(!d.dueAt)continue;const exists=repo.state.deadlines.some(x=>x.courseId===course!.id&&x.title===d.title&&x.dueAt===d.dueAt);if(!exists)repo.state.deadlines.push({id:uid(),courseId:course.id,title:d.title||'موعد أكاديمي',kind:['exam','assignment','presentation','other'].includes(d.kind)?d.kind:'other',dueAt:d.dueAt,done:false})}repo.addArtifact({courseId:course.id,type:'syllabus',title:`سيلابس — ${course.name}`,truth:'supported',data});repo.persist();const plans=loadPlans();if((data.grading||[]).length&&!plans[course.id]){plans[course.id]={target:70,items:(data.grading||[]).map((g:any)=>({id:uid(),name:g.name||'تقييم',weight:Number(g.weight)||0,score:''}))};savePlans(plans)}notify('أضفت المادة والمواعيد وتوزيع الدرجات إلى ScholarMCP')}
 return <div className="syllabus-layout"><div className="panel syllabus-drop"><input ref={input} hidden type="file" accept=".pdf,.docx,.pptx,.txt,.md,.jpg,.jpeg,.png,.webp,image/*" onChange={e=>{const f=e.target.files?.[0];if(f)run(f)}}/><Sparkles/><h3>ارمِ السيلابس وانساه</h3><p>ScholarMCP يستخرج اسم المادة، الامتحانات، الواجبات، توزيع الدرجات والمواضيع الأسبوعية.</p><button className="primary" onClick={()=>input.current?.click()} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Upload/>} {busy?'أحلل السيلابس…':'ارفع السيلابس'}</button>{file&&<small>{file.name}</small>}</div>{data&&<div className="panel syllabus-result"><div className="section-head"><div><h3>{data.courseName||'المادة'}</h3><p>{data.instructor||'لم يُذكر المدرس'} {data.term&&`• ${data.term}`}</p></div><button className="primary" onClick={apply}><Save/> طبّق على منصتي</button></div><h4>توزيع الدرجات</h4><div className="grade-chips">{(data.grading||[]).map((g:any,i:number)=><span key={i}>{g.name} <b>{g.weight}%</b></span>)}</div><h4>المواعيد</h4><div className="deadline-preview">{(data.deadlines||[]).map((d:any,i:number)=><div key={i}><CalendarDays/><div><b>{d.title}</b><small>{d.dueAt||'بدون تاريخ واضح'}</small></div></div>)}{!(data.deadlines||[]).length&&<p className="muted">ما لقيت مواعيد صريحة.</p>}</div><h4>خريطة الأسابيع</h4><div className="week-grid">{(data.weeks||[]).slice(0,16).map((w:any,i:number)=><div key={i}><b>الأسبوع {w.week||i+1}</b><p>{(w.topics||[]).join(' • ')}</p></div>)}</div>{(data.warnings||[]).length>0&&<div className="warning">{data.warnings.join(' • ')}</div>}</div>}</div>
}

function GradePlanner({state,notify}:Props){const [plans,setPlans]=useState<GradePlans>(()=>loadPlans());const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const plan=plans[courseId]||{target:70,items:[]};function update(next:any){const all={...plans,[courseId]:next};setPlans(all);savePlans(all)}function add(){update({...plan,items:[...plan.items,{id:uid(),name:'تقييم جديد',weight:10,score:''}]})}function remove(id:string){update({...plan,items:plan.items.filter(x=>x.id!==id)})}const calc=useMemo(()=>{let earned=0,used=0;for(const x of plan.items){if(x.score===''||!Number.isFinite(Number(x.score)))continue;earned+=(Number(x.score)/100)*Number(x.weight||0);used+=Number(x.weight||0)}const remaining=Math.max(0,100-used);const needed=remaining?Math.max(0,(plan.target-earned)/remaining*100):0;return{earned,used,remaining,needed}},[plan]);if(!state.courses.length)return <div className="panel empty-grade"><BookOpen/><h3>أضف مادة أولًا</h3><p>بعدها أحسب لك وين واقف وشنو تحتاج بالفاينل.</p></div>;return <div className="grade-planner"><div className="panel"><div className="grade-toolbar"><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label>هدفي <input type="number" min="0" max="100" value={plan.target} onChange={e=>update({...plan,target:Number(e.target.value)})}/>%</label><button className="ghost" onClick={add}><Plus/> إضافة تقييم</button></div><div className="grade-table"><div className="grade-row head"><span>التقييم</span><span>الوزن %</span><span>درجتك %</span><span/></div>{plan.items.map(x=><div className="grade-row" key={x.id}><input value={x.name} onChange={e=>update({...plan,items:plan.items.map(i=>i.id===x.id?{...i,name:e.target.value}:i)})}/><input type="number" min="0" max="100" value={x.weight} onChange={e=>update({...plan,items:plan.items.map(i=>i.id===x.id?{...i,weight:Number(e.target.value)}:i)})}/><input type="number" min="0" max="100" placeholder="—" value={x.score} onChange={e=>update({...plan,items:plan.items.map(i=>i.id===x.id?{...i,score:e.target.value}:i)})}/><button className="danger compact" onClick={()=>remove(x.id)}><Trash2/></button></div>)}</div></div><div className="grade-metrics"><div><small>مجموع الأوزان المحسوبة</small><b>{calc.used.toFixed(0)}%</b></div><div><small>المحصّل من 100</small><b>{calc.earned.toFixed(1)}</b></div><div className={calc.needed>100?'bad':'good'}><small>تحتاج في المتبقي حتى توصل {plan.target}%</small><b>{calc.remaining?`${calc.needed.toFixed(1)}%`:'—'}</b></div></div>{calc.needed>100&&<div className="warning">الهدف الحالي غير ممكن حسابيًا بالدرجات المتبقية. غيّر الهدف أو راجع الأوزان.</div>}<button className="primary save-grade" onClick={()=>notify('حفظت خطة الدرجات على جهازك')}><CheckCircle2/> الخطة محفوظة تلقائيًا</button></div>}
