function textOf(value:any){if(typeof value==='string')return value;if(typeof value?.text==='string')return value.text;const c=value?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map((x:any)=>x?.text||'').join('\n');return ''}
function parse(text:string){const s=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw new Error('التحليل رجع بصيغة غير مفهومة. حاول مرة ثانية.')}
async function puter(){for(let i=0;i<80;i++){const p=(window as any).puter;if(p?.ai?.chat)return p;await new Promise(r=>setTimeout(r,100))}throw new Error('محرك Scholar AI السحابي غير متاح. تحقق من الإنترنت.')}
async function jsonChat(prompt:string){const p=await puter();let r:any;try{r=await p.ai.chat(prompt,{model:'gpt-5-nano'})}catch{r=await p.ai.chat(prompt)}const t=textOf(r);if(!t)throw new Error('لم يصل رد من Scholar AI.');return parse(t)}
const ground=`أنت وكيل أكاديمي داخل ScholarMCP. لا تخترع بيانات غير موجودة في النص. أعد JSON صالحاً فقط بلا markdown. إذا كانت قيمة غير موجودة ضع null أو مصفوفة فارغة.`;

export async function analyzeSyllabus(text:string){return jsonChat(`${ground}\nحلل هذا السيلابس/وصف المقرر. استخرج اسم المادة، المواعيد، الامتحانات، الواجبات، السيمنارات، توزيع الدرجات، المواضيع الأسبوعية، وأي تعليمات مهمة. التواريخ يجب أن تكون YYYY-MM-DD إذا أمكن.\nأعد بالضبط: {"courseName":"","instructor":null,"term":null,"grading":[{"name":"","weight":0}],"deadlines":[{"title":"","kind":"exam|assignment|presentation|other","dueAt":"YYYY-MM-DD"}],"weeks":[{"week":1,"topics":[""]}],"rules":[""],"warnings":[""]}.\nSOURCE:\n${text.slice(0,70000)}`)}
export async function analyzeExamDNA(text:string){return jsonChat(`${ground}\nهذه مجموعة امتحانات أو أسئلة سابقة. حلل النمط فقط ولا تدّعِ توقع الأسئلة المستقبلية. استخرج أنواع الأسئلة وتكرار المواضيع والصعوبة وصياغة المدرس والمهارات المطلوبة.\nأعد {"questionTypes":[{"type":"","share":0}],"repeatedTopics":[{"topic":"","frequency":0}],"difficulty":"easy|medium|hard|mixed","styleNotes":[""],"skills":["recall|understanding|application|analysis"],"recommendations":[""],"sampleBlueprint":{"mcq":0,"trueFalse":0,"shortAnswer":0,"essay":0,"case":0}}.\nSOURCE:\n${text.slice(0,70000)}`)}
export async function buildSeminarRehearsal(title:string,slides:Array<{title:string;bullets?:string[];notes?:string}>){return jsonChat(`${ground}\nجهز الطالب للدفاع عن سيمنار بعنوان ${title}. بناءً على الشرائح التالية، ولّد أسئلة محتملة من المدرس، أجوبة قصيرة موثوقة من محتوى العرض، ونقاط يجب أن ينتبه لها أثناء الإلقاء.\nأعد {"questions":[{"question":"","answer":"","slide":1}],"deliveryTips":[""],"opening":"","closing":""}.\nSLIDES:\n${JSON.stringify(slides).slice(0,50000)}`)}
