import { useEffect, useMemo, useRef, useState, type ComponentType, type CSSProperties } from 'react';
import {
  BookOpen, Brain, CalendarDays, CheckCircle2, CircleAlert, Download, ExternalLink,
  FileText, GraduationCap, Languages, Library, LoaderCircle, Menu, MessageSquareText,
  Plus, Search, Settings, Sparkles, Trash2, Upload, X, Youtube, ClipboardList, Home,
  Eye, Presentation, ThumbsUp, GitBranch, FileQuestion, Layers3, RefreshCw
} from 'lucide-react';
import {
  type AppState, type Course, type Material, type Artifact, type Flashcard,
  LocalRepository, parseFile, humanSize, fmtDate, daysUntil, courseMastery, riskScore,
  weakest, retrieve, aiTask, researchCrossref, youtubeUrl, exportDocx, exportPptx
} from './lib';

type View='today'|'courses'|'course'|'study'|'assignments'|'research'|'library'|'calendar'|'settings';
type CourseTab='overview'|'topics'|'sources'|'performance';
const repo=new LocalRepository();
const nav:[View,string,ComponentType][]=[
  ['today','اليوم',Home],['courses','موادي',BookOpen],['study','الدراسة',Brain],
  ['assignments','الواجبات',ClipboardList],['research','البحث',Search],['library','مكتبتي',Library],
  ['calendar','جدولي',CalendarDays],['settings','الإعدادات',Settings]
];

function clone<T>(v:T):T{try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v)) as T}}
function useData(){
  const [state,setState]=useState<AppState>(clone(repo.state));
  useEffect(()=>{const refresh=()=>setState(clone(repo.state));window.addEventListener('scholar-state',refresh);return()=>window.removeEventListener('scholar-state',refresh)},[]);
  return state;
}

export default function App(){
  const state=useData();
  const [view,setView]=useState<View>('today');
  const [courseId,setCourseId]=useState<string>();
  const [studyCourseId,setStudyCourseId]=useState<string>();
  const [drawer,setDrawer]=useState(false);
  const [lens,setLens]=useState<Material|null>(null);
  const [toast,setToast]=useState('');
  const [searchOpen,setSearchOpen]=useState(false);
  const [searchQ,setSearchQ]=useState('');
  const active=state.courses.find(c=>c.id===courseId)||null;
  const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),3200)};
  const go=(v:View)=>{setView(v);setDrawer(false)};
  const openCourse=(c:Course)=>{setCourseId(c.id);setView('course');setSearchOpen(false)};
  const openStudy=(id?:string)=>{setStudyCourseId(id||state.courses[0]?.id);setView('study');setDrawer(false)};
  if(!state.profile.onboarded)return <Onboarding/>;
  return <div className="app-shell" dir="rtl">
    <Sidebar state={state} view={view} go={go} drawer={drawer} setDrawer={setDrawer}/>
    <MobileNav view={view} go={go} setDrawer={setDrawer}/>
    <main><Topbar setDrawer={setDrawer} onSearch={(q)=>{setSearchQ(q);setSearchOpen(!!q.trim())}}/><div className="content">
      {view==='today'&&<Today state={state} openCourse={openCourse} openStudy={openStudy} go={go}/>} 
      {view==='courses'&&<Courses state={state} openCourse={openCourse} notify={notify}/>} 
      {view==='course'&&active&&<CourseWorkspace state={state} course={active} openLens={setLens} startStudy={()=>openStudy(active.id)} notify={notify}/>} 
      {view==='course'&&!active&&<Empty title="اختر مادة أولًا" icon={BookOpen}/>} 
      {view==='study'&&<Study state={state} initialCourseId={studyCourseId} notify={notify}/>} 
      {view==='assignments'&&<Assignments state={state} notify={notify}/>} 
      {view==='research'&&<Research/>} 
      {view==='library'&&<LibraryView state={state} openLens={setLens} openCourse={openCourse}/>} 
      {view==='calendar'&&<CalendarView state={state}/>} 
      {view==='settings'&&<SettingsView state={state}/>} 
    </div></main>
    {lens&&<SourceLens material={lens} onClose={()=>setLens(null)}/>} 
    {searchOpen&&<GlobalSearch state={state} q={searchQ} openCourse={openCourse} openLens={setLens} close={()=>setSearchOpen(false)}/>} 
    {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  </div>;
}

function Onboarding(){
  const [name,setName]=useState('');const [major,setMajor]=useState('');const [lang,setLang]=useState<'ar'|'en'>('ar');
  return <div className="onboard"><div className="brand-large"><div className="logo"><GraduationCap/></div><b>Scholar<span>MCP</span></b></div><div className="onboard-card"><span className="eyebrow">ACADEMIC OS</span><h1>من أول محاضرة إلى آخر امتحان.</h1><p className="muted">رتّب موادك ومصادرك ودراستك في عقل أكاديمي واحد.</p><label>اسمك<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: علي"/></label><label>التخصص — اختياري<input value={major} onChange={e=>setMajor(e.target.value)} placeholder="الأدلة الجنائية"/></label><label>لغة الشرح الافتراضية<select value={lang} onChange={e=>setLang(e.target.value as 'ar'|'en')}><option value="ar">العربية</option><option value="en">English</option></select></label><button className="primary wide" disabled={!name.trim()} onClick={()=>repo.setProfile({name:name.trim(),major:major.trim()||undefined,studyLanguage:lang,onboarded:true})}>ابدأ منصتي</button></div></div>;
}

function Sidebar({state,view,go,drawer,setDrawer}:{state:AppState;view:View;go:(v:View)=>void;drawer:boolean;setDrawer:(x:boolean)=>void}){
  return <><aside className={`sidebar ${drawer?'open':''}`}><div className="brand"><div className="logo"><GraduationCap/></div><div><b>Scholar<span>MCP</span></b><small>نظامك الأكاديمي الذكي</small></div></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?'active':''} onClick={()=>go(id)}><I/><span>{label}</span></button>)}</nav><div className="side-profile"><div className="avatar">{state.profile.name.slice(0,1)||'ط'}</div><div><b>{state.profile.name}</b><small>{state.profile.major||'طالب جامعي'}</small></div></div></aside>{drawer&&<div className="overlay" onClick={()=>setDrawer(false)}/>}</>;
}
function MobileNav({view,go,setDrawer}:{view:View;go:(v:View)=>void;setDrawer:(x:boolean)=>void}){return <nav className="mobile-nav">{nav.slice(0,5).map(([id,label,I])=><button key={id} className={view===id?'active':''} onClick={()=>go(id)}><I/><span>{label}</span></button>)}<button onClick={()=>setDrawer(true)}><Menu/><span>المزيد</span></button></nav>}
function Topbar({setDrawer,onSearch}:{setDrawer:(x:boolean)=>void;onSearch:(q:string)=>void}){const [q,setQ]=useState('');return <header className="top-search"><button className="menu" onClick={()=>setDrawer(true)}><Menu/></button><Search/><input value={q} onChange={e=>{setQ(e.target.value);onSearch(e.target.value)}} placeholder="ابحث في المواد والملفات..."/><span className="muted">AI + OCR</span></header>}

function Today({state,openCourse,openStudy,go}:{state:AppState;openCourse:(c:Course)=>void;openStudy:(id?:string)=>void;go:(v:View)=>void}){
  const risk=state.courses.slice().sort((a,b)=>riskScore(state,b)-riskScore(state,a))[0];
  const weak=risk?weakest(state,risk.id):[];
  const due=state.flashcards.filter(f=>new Date(f.dueAt).getTime()<=Date.now()).length;
  const deadlines=state.deadlines.filter(d=>!d.done).slice().sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)).slice(0,4);
  return <section><div className="welcome"><span className="eyebrow">TODAY</span><h1>هلا {state.profile.name} 👋</h1><p>المادة الأقرب والخطوة الأعلى عائدًا تظهر هنا.</p></div>{risk?<><div className="hero-course"><div className="hero-copy"><span className="eyebrow">الأولوية الحالية</span><h2>{risk.name}</h2><span className="badge-risk">مؤشر الخطر {riskScore(state,risk)}%</span><div className="mastery-bar"><span style={{width:`${courseMastery(state,risk.id)}%`}}/></div><p>الإتقان {courseMastery(state,risk.id)}% • {risk.examDate?`باقي ${Math.max(0,daysUntil(risk.examDate)||0)} يوم`:'لا يوجد موعد امتحان'}</p><div className="export-inline"><button className="primary" onClick={()=>openStudy(risk.id)}><Brain/> ابدأ الدراسة</button><button className="ghost" onClick={()=>openCourse(risk)}><BookOpen/> افتح المادة</button></div></div><div className="weak-card"><b>نقاط تحتاج تركيز</b>{weak.length?weak.map(t=><p key={t.id}>{t.title} — {t.mastery}%</p>):<p>اختبر نفسك أولًا حتى نبني نقاط الضعف.</p>}</div></div><div className="today-grid"><div className="metric"><b>{due}</b><small>بطاقات مستحقة</small></div><div className="metric"><b>{state.materials.length}</b><small>مصادر مرفوعة</small></div><div className="metric"><b>{state.assignments.length}</b><small>واجبات محفوظة</small></div></div><div className="panel"><div className="section-head"><div><h3>القادم</h3><p>امتحانات وتسليمات حسب القرب.</p></div><button className="ghost" onClick={()=>go('calendar')}>فتح الجدول</button></div><div className="deadline-list">{deadlines.length?deadlines.map(d=><div key={d.id}><CalendarDays/><div><b>{d.title}</b><small>{fmtDate(d.dueAt)}</small></div></div>):<p className="muted">ماكو مواعيد محفوظة بعد.</p>}</div></div></>:<Empty title="أضف أول مادة" text="ScholarMCP يبدأ من المادة ثم المصدر." icon={BookOpen} action={()=>go('courses')} actionLabel="إضافة مادة"/>}</section>;
}

function Courses({state,openCourse,notify}:{state:AppState;openCourse:(c:Course)=>void;notify:(m:string)=>void}){
  const [name,setName]=useState('');const [exam,setExam]=useState('');const [q,setQ]=useState('');
  const list=state.courses.filter(c=>c.name.toLowerCase().includes(q.toLowerCase()));
  function add(){if(!name.trim())return;repo.addCourse(name.trim(),exam||undefined);setName('');setExam('');notify('تم إنشاء المادة')}
  return <section><div className="section-head page"><div><span className="eyebrow">COURSE BRAINS</span><h1>موادي</h1><p>كل مادة تجمع مصادرها، اختباراتك ونقاط ضعفك.</p></div></div><div className="new-course"><input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المادة"/><input type="date" value={exam} onChange={e=>setExam(e.target.value)}/><button className="primary" onClick={add}><Plus/> إضافة مادة</button></div><div className="filter"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالمواد..."/></div><div className="course-grid">{list.map(c=><article className="course-card" key={c.id}><button className="course-icon" onClick={()=>openCourse(c)}><BookOpen/></button><button className="course-main" onClick={()=>openCourse(c)}><h3>{c.name}</h3><p>{c.examDate?fmtDate(c.examDate):'بدون موعد امتحان'}</p><div className="mini-progress"><span style={{width:`${courseMastery(state,c.id)}%`}}/></div></button><button className="danger" onClick={()=>confirm(`حذف ${c.name} وكل بياناتها؟`)&&repo.deleteCourse(c.id)}><Trash2/></button></article>)}</div>{!list.length&&<Empty title="ماكو مواد مطابقة" icon={BookOpen}/>}</section>;
}

function CourseWorkspace({state,course,openLens,startStudy,notify}:{state:AppState;course:Course;openLens:(m:Material)=>void;startStudy:()=>void;notify:(m:string)=>void}){
  const mats=state.materials.filter(m=>m.courseId===course.id);const topics=state.topics.filter(t=>t.courseId===course.id);const artifacts=state.artifacts.filter(a=>a.courseId===course.id);const cards=state.flashcards.filter(f=>f.courseId===course.id);
  const [tab,setTab]=useState<CourseTab>('overview');const [busy,setBusy]=useState('');const [quiz,setQuiz]=useState<any[]>([]);const [artifact,setArtifact]=useState<Artifact|null>(null);const [cardsOpen,setCardsOpen]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  const ready=mats.filter(m=>m.status==='ready'&&m.text.trim());
  const context=()=>ready.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n').slice(0,120000);
  async function upload(files:FileList|null){if(!files)return;for(const file of [...files]){setBusy('upload');notify(`جاري فهم ${file.name}…`);const parsed=await parseFile(file);repo.addMaterial({courseId:course.id,name:file.name,mime:file.type,ext:file.name.split('.').pop()?.toLowerCase()||'',size:file.size,pages:parsed.pages,status:parsed.text?'ready':'failed',error:parsed.error,text:parsed.text});notify(parsed.text?`تمت قراءة ${file.name}${parsed.error?' مع ملاحظة':''}`:`تعذر فهم ${file.name}`)}setBusy('')}
  async function generate(type:'summary'|'translation'|'mindmap'|'flashcards'|'quiz'|'package'){
    if(!ready.length){notify('ارفع مصدرًا قابلًا للقراءة أولًا');setTab('sources');return}
    setBusy(type);try{const ctx=context();
      if(type==='summary'){const d:any=await aiTask('summary',{context:ctx});const a=repo.addArtifact({courseId:course.id,type:'summary',title:`ملخص ${course.name}`,truth:'supported',coverage:d.estimatedCoverage,data:d});repo.upsertTopics(course.id,(d.keyConcepts||[]).map((x:any)=>({title:x.title,sourceRef:x.sourceRef})));setArtifact(a)}
      if(type==='translation'){const target=window.prompt('إلى أي لغة تريد ترجمة المادة؟','العربية')||'العربية';const d:any=await aiTask('translate',{context:ctx,target});setArtifact(repo.addArtifact({courseId:course.id,type:'translation',title:`ترجمة ${course.name} — ${target}`,truth:'supported',data:d}))}
      if(type==='mindmap'){const d:any=await aiTask('mindmap',{context:ctx});setArtifact(repo.addArtifact({courseId:course.id,type:'mindmap',title:`خريطة ${course.name}`,truth:'supported',data:d}))}
      if(type==='flashcards'){const d:any=await aiTask('flashcards',{context:ctx,count:14});repo.addFlashcards(course.id,d.cards||[]);setCardsOpen(true);notify('تم إنشاء بطاقات من محتوى المصدر')}
      if(type==='quiz'){const d:any=await aiTask('quiz',{context:ctx,count:8});if(!(d.questions||[]).length)throw new Error('ما قدرت أبني اختبار مناسب');setQuiz(d.questions||[])}
      if(type==='package'){const d:any=await aiTask('package',{context:ctx,topic:course.name});setArtifact(repo.addArtifact({courseId:course.id,type:'package',title:`الحقيبة الأكاديمية — ${course.name}`,truth:'supported',data:d}))}
    }catch(e){notify((e as Error).message||'تعذرت المعالجة')}finally{setBusy('')}
  }
  return <section><div className="course-hero"><div><span className="eyebrow">COURSE BRAIN</span><h1>{course.name}</h1><p>{course.examDate?`الامتحان ${fmtDate(course.examDate)} • ${Math.max(0,daysUntil(course.examDate)||0)} يوم متبقي`:'لم تحدد موعد الامتحان'}</p></div><div className="score-ring" style={{'--score':`${courseMastery(state,course.id)}%`} as CSSProperties}><span>{courseMastery(state,course.id)}%</span></div></div>
  <div className="action-grid"><button onClick={startStudy}><Brain/> ادرس الآن</button><button onClick={()=>generate('quiz')}><FileQuestion/> اختبرني</button><button onClick={()=>generate('summary')}><Sparkles/> ملخص وشرح</button><button onClick={()=>generate('translation')}><Languages/> ترجمة كاملة</button></div>
  <div className="tabs">{([['overview','نظرة عامة'],['topics','المفاهيم'],['sources','المصادر'],['performance','الأداء']] as [CourseTab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='overview'&&<><div className="panel"><div className="section-head"><div><h3>أدوات المادة</h3><p>كل أداة تستخدم نفس المصدر الذي رفعته.</p></div></div><div className="studio-grid"><button onClick={()=>generate('flashcards')}><ClipboardList/> إنشاء بطاقات</button><button onClick={()=>cards.length?setCardsOpen(true):generate('flashcards')}><Layers3/> مراجعة البطاقات ({cards.length})</button><button onClick={()=>generate('mindmap')}><GitBranch/> خريطة ذهنية</button><button onClick={()=>generate('package')}><Presentation/> حقيبة أكاديمية</button><a className="ghost" href={youtubeUrl(course.name)} target="_blank" rel="noreferrer"><Youtube/> شرح على YouTube</a></div></div><CourseChat materials={ready}/><div className="panel"><h3>آخر المخرجات</h3><div className="artifact-list">{artifacts.slice(0,6).map(a=><button key={a.id} onClick={()=>setArtifact(a)}><Sparkles/><div><b>{a.title}</b><small>{new Date(a.createdAt).toLocaleString('ar-IQ')}</small></div></button>)}</div>{!artifacts.length&&<p className="muted">ابدأ بملخص وشرح حتى يبني ScholarMCP خريطة المادة.</p>}</div></>}
  {tab==='topics'&&<div className="panel"><div className="topic-list">{topics.map(t=><div key={t.id}><Brain/><div><b>{t.title}</b><small>{t.sourceRef||'مرجع الصفحة غير محدد'}</small></div><span className="topic-score">{t.mastery}%</span></div>)}</div>{!topics.length&&<Empty title="المفاهيم تظهر بعد الملخص والاختبارات" icon={Brain}/>}</div>}
  {tab==='sources'&&<div className="panel"><div className="section-head"><div><h3>مصادر المادة</h3><p>يدعم النص، PDF، Word، PowerPoint، الصور، والـPDF الممسوح. الصفحات التي لا تحتوي نصًا تمر على OCR يدعم المطبوع والخط اليدوي.</p></div><button className="primary" onClick={()=>inputRef.current?.click()}><Upload/> إضافة ملف/صورة</button></div><input ref={inputRef} type="file" hidden multiple accept=".pdf,.docx,.pptx,.txt,.md,.jpg,.jpeg,.png,.webp,.bmp,image/*" onChange={e=>upload(e.target.files)}/>{busy==='upload'&&<div className="ai-loading"><LoaderCircle className="spin"/> جاري استخراج النص وOCR… قد يأخذ وقتًا مع الصفحات المصورة.</div>}<div className="material-list">{mats.map(m=><article key={m.id}><FileText/><div style={{flex:1,overflow:'hidden'}}><b style={{overflowWrap:'anywhere'}}>{m.name}</b><small>{humanSize(m.size)} • {m.pages} صفحة • {m.status==='ready'?'جاهز للدراسة':'تعذر'}</small>{m.error&&<div className="warning"><CircleAlert/>{m.error}</div>}</div><div className="mat-actions"><button className="ghost compact" onClick={()=>openLens(m)}><Eye/> فتح النص</button><button className="danger compact" onClick={()=>confirm('حذف هذا المصدر؟')&&repo.deleteMaterial(m.id)}><Trash2/></button></div></article>)}</div>{!mats.length&&<Empty title="ارفع أول ملزمة أو صورة" text="إذا كانت الصفحة مكتوبة بخط اليد أو صورة، يشتغل OCR تلقائيًا." icon={Upload}/>}</div>}
  {tab==='performance'&&<div className="health-grid"><div><b>الإتقان</b><h2>{courseMastery(state,course.id)}%</h2></div><div><b>المفاهيم</b><h2>{topics.length}</h2></div><div><b>المصادر</b><h2>{mats.length}</h2></div><div><b>البطاقات</b><h2>{cards.length}</h2></div></div>}
  {busy&&busy!=='upload'&&<div className="ai-loading"><LoaderCircle className="spin"/> الذكاء يقرأ المصدر ويبني النتيجة…</div>}
  {quiz.length>0&&<QuizModal course={course} questions={quiz} onClose={()=>setQuiz([])} notify={notify}/>} {artifact&&<ArtifactModal art={artifact} onClose={()=>setArtifact(null)}/>} {cardsOpen&&<FlashcardsModal cards={state.flashcards.filter(f=>f.courseId===course.id)} onClose={()=>setCardsOpen(false)}/>}</section>;
}

function CourseChat({materials}:{materials:Material[]}){
  const [question,setQuestion]=useState('');const [messages,setMessages]=useState<Array<{role:'user'|'assistant';text:string;truth?:string}>>([]);const [busy,setBusy]=useState(false);
  async function ask(){if(!question.trim()||!materials.length)return;const q=question.trim();setMessages(m=>[...m,{role:'user',text:q}]);setQuestion('');setBusy(true);try{const hits=retrieve(materials,q,10);const context=hits.map(h=>`SOURCE ${h.material} [[PAGE ${h.page}]]\n${h.text}`).join('\n\n');const r:any=await aiTask('chat',{question:q,context});setMessages(m=>[...m,{role:'assistant',text:String(r.text||'تعذر توليد الإجابة.'),truth:typeof r.truth==='string'?r.truth:undefined}])}catch(e){setMessages(m=>[...m,{role:'assistant',text:`تعذر: ${(e as Error).message}`,truth:'unverified'}])}finally{setBusy(false)}}
  return <div className="panel chat-panel"><div className="section-head"><div><h3>اسأل المادة</h3><p>اسأل شرح، مقارنة، مثال أو معنى مصطلح. الإجابة مربوطة بالمصدر.</p></div><span className="truth supported">AI grounded</span></div><div className="messages">{!messages.length&&<div className="chat-empty"><MessageSquareText/><p>{materials.length?'مثال: اشرحلي هذا الفصل كأني أدرسه أول مرة، ولا تخرج عن المصدر.':'ارفع مصدرًا أولًا.'}</p></div>}{messages.map((m,i)=><div className={`message ${m.role}`} key={i}>{m.truth&&<span className={`truth ${m.truth}`}>{m.truth}</span>}<p>{m.text}</p></div>)}{busy&&<div className="typing"><LoaderCircle className="spin"/> أقرأ المصدر…</div>}</div><div className="chat-input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="اكتب سؤالك عن المادة…"/><button onClick={ask} disabled={busy||!materials.length}><Sparkles/></button></div></div>;
}

const modeLabels={learn:'تعلم أول مرة',review:'مراجعة',test:'تثبيت واختبار',rescue:'إنقاذ قبل الامتحان'} as const;
function Study({state,initialCourseId,notify}:{state:AppState;initialCourseId?:string;notify:(m:string)=>void}){
  const [courseId,setCourseId]=useState(initialCourseId||state.courses[0]?.id||'');const [mode,setMode]=useState<keyof typeof modeLabels>('learn');const [steps,setSteps]=useState<Array<{title:string;detail:string;done:boolean}>>([]);const [busy,setBusy]=useState(false);const [quiz,setQuiz]=useState<any[]>([]);
  useEffect(()=>{if(initialCourseId)setCourseId(initialCourseId)},[initialCourseId]);
  const course=state.courses.find(c=>c.id===courseId);const mats=state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text);const weak=weakest(state,courseId);const context=()=>mats.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n').slice(0,120000);
  async function build(){if(!course||!mats.length){notify('اختر مادة وارفع لها مصدرًا أولًا');return}setBusy(true);try{const r:any=await aiTask('study',{context:context(),mode,weakTopics:weak.map(x=>x.title),daysToExam:daysUntil(course.examDate)});setSteps((r.steps||[]).map((x:any)=>({...x,done:false})))}finally{setBusy(false)}}
  async function makeQuiz(){if(!mats.length)return;setBusy(true);try{const r:any=await aiTask('quiz',{context:context(),count:8});setQuiz(r.questions||[])}finally{setBusy(false)}}
  return <section><div className="section-head page"><div><span className="eyebrow">ADAPTIVE STUDY</span><h1>جلسة الدراسة</h1><p>اختر الوضع؛ الذكاء يبني المحتوى من ملازمك ونقاط ضعفك.</p></div></div><div className="study-config"><label>المادة<select value={courseId} onChange={e=>{setCourseId(e.target.value);setSteps([])}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="mode-grid">{(Object.keys(modeLabels) as Array<keyof typeof modeLabels>).map(x=><button key={x} className={mode===x?'active':''} onClick={()=>setMode(x)}>{modeLabels[x]}</button>)}</div><button className="primary" onClick={build} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Brain/>} بناء جلسة من المصدر</button></div>{course&&<div className="study-context"><div><b>{course.name}</b><small>الإتقان {courseMastery(state,course.id)}% • {mats.length} مصدر</small></div><span>{course.examDate?`${Math.max(0,daysUntil(course.examDate)||0)} يوم للامتحان`:'بدون موعد'}</span></div>}<div className="study-steps">{steps.map((s,i)=><button key={i} className={s.done?'done':''} onClick={()=>setSteps(x=>x.map((v,j)=>j===i?{...v,done:!v.done}:v))}><span>{s.done?'✓':i+1}</span><div><b>{s.title}</b><p>{s.detail}</p></div></button>)}</div>{steps.length>0&&<div className="panel"><div className="section-head"><div><h3>اختبر فهمك الآن</h3><p>الاختبار يولد من نفس المصدر الذي درست منه.</p></div><button className="primary" onClick={makeQuiz}><FileQuestion/> ابدأ اختبارًا</button></div></div>}{!steps.length&&<Empty title="اختر المادة واضغط بناء جلسة من المصدر" icon={Brain}/>} {quiz.length>0&&course&&<QuizModal course={course} questions={quiz} onClose={()=>setQuiz([])} notify={notify}/>}</section>;
}

function Assignments({state,notify}:{state:AppState;notify:(m:string)=>void}){
  const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [title,setTitle]=useState('');const [instructions,setInstructions]=useState('');const [rubric,setRubric]=useState('');const [due,setDue]=useState('');const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);
  async function run(){if(!courseId||!instructions.trim())return;const mats=state.materials.filter(m=>m.courseId===courseId&&m.status==='ready');setBusy(true);try{const context=mats.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n').slice(0,120000);const r:any=await aiTask('assignment',{context,instructions,rubric});setResult(r);repo.addAssignment({courseId,title:title||'واجب أكاديمي',instructions,rubric,dueAt:due||undefined,checklist:Array.isArray(r.checklist)?r.checklist:[],outline:typeof r.outline==='string'?r.outline:Array.isArray(r.outline)?r.outline.join('\n'):undefined,draft:typeof r.draft==='string'?r.draft:undefined,assessment:r.assessment});notify('تم تحليل الواجب وحفظه')}finally{setBusy(false)}}
  return <section><div className="section-head page"><div><span className="eyebrow">ACADEMIC EXECUTION</span><h1>الواجبات والتسليم</h1><p>ارفع المصادر ثم الصق تعليمات الدكتور والـRubric.</p></div></div><div className="assignment-form"><label>المادة<select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>عنوان الواجب<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>الموعد<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className="span2">التعليمات<textarea value={instructions} onChange={e=>setInstructions(e.target.value)}/></label><label className="span2">Rubric<textarea value={rubric} onChange={e=>setRubric(e.target.value)}/></label><button className="primary span2" onClick={run} disabled={busy||!instructions.trim()}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>} تحليل وبناء المسودة</button></div>{result&&<div className="assignment-result"><section className="panel"><h3>المتطلبات</h3>{(result.checklist||[]).map((x:any,i:number)=><div className="check-row" key={i}><CheckCircle2/><span>{x.text}</span></div>)}</section><section className="panel draft"><div className="section-head"><h3>المسودة</h3><button className="ghost" onClick={()=>exportDocx(title||'ScholarMCP Assignment',result.draft||'')}><Download/> Word</button></div><pre>{result.draft}</pre></section></div>}</section>;
}

function Research(){const [q,setQ]=useState('');const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');async function search(){if(!q.trim())return;setBusy(true);setErr('');try{setRows(await researchCrossref(q.trim()))}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}return <section><div className="research-hero"><span className="eyebrow">REAL METADATA • CROSSREF</span><h1>البحث الأكاديمي</h1><p>نتائج DOI حقيقية؛ لا توجد مراجع مختلقة.</p><div className="research-search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="مثال: forensic toxicology biomarkers"/><button className="primary" onClick={search}>{busy?<LoaderCircle className="spin"/>:<Search/>} بحث</button></div></div>{err&&<div className="error"><CircleAlert/>{err}</div>}<div className="paper-list">{rows.map((p,i)=><article key={`${p.doi}-${i}`}><span className="paper-num">{i+1}</span><h3>{p.title}</h3><p>{p.authors?.join(', ')} • {p.year||'n.d.'} • {p.journal}</p><p>{p.citation}</p>{p.url&&<a href={p.url} target="_blank" rel="noreferrer"><ExternalLink/> فتح DOI</a>}</article>)}</div></section>}

function LibraryView({state,openLens,openCourse}:{state:AppState;openLens:(m:Material)=>void;openCourse:(c:Course)=>void}){return <section><div className="section-head page"><div><span className="eyebrow">LIBRARY</span><h1>مكتبتي</h1><p>كل الملفات مربوطة بموادها.</p></div></div><div className="library-grid">{state.materials.map(m=><button key={m.id} onClick={()=>openLens(m)}><span className="file-badge"><FileText/></span><div><b>{m.name}</b><small>{state.courses.find(c=>c.id===m.courseId)?.name} • {humanSize(m.size)}</small></div></button>)}</div>{!state.materials.length&&<Empty title="مكتبتك فارغة" icon={Library}/>}<div className="panel"><h3>المواد</h3><div className="artifact-list">{state.courses.map(c=><button key={c.id} onClick={()=>openCourse(c)}><BookOpen/><div><b>{c.name}</b><small>{state.materials.filter(m=>m.courseId===c.id).length} ملفات</small></div></button>)}</div></div></section>}
function CalendarView({state}:{state:AppState}){const list=state.deadlines.slice().sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt));return <section><div className="section-head page"><div><span className="eyebrow">CALENDAR</span><h1>جدولي</h1><p>امتحانات وتسليماتك.</p></div></div><div className="calendar-list">{list.map(d=><div key={d.id}><span className="datebox">{new Date(d.dueAt).getDate()}<small>{new Intl.DateTimeFormat('ar-IQ',{month:'short'}).format(new Date(d.dueAt))}</small></span><div><b>{d.title}</b><small>{state.courses.find(c=>c.id===d.courseId)?.name||d.kind}</small></div></div>)}</div>{!list.length&&<Empty title="ماكو مواعيد بعد" icon={CalendarDays}/>}</section>}
function SettingsView({state}:{state:AppState}){return <section><div className="section-head page"><div><span className="eyebrow">SETTINGS</span><h1>الإعدادات</h1></div></div><div className="settings-grid"><section className="panel"><h3>الملف الأكاديمي</h3><p><b>{state.profile.name}</b></p><p>{state.profile.major||'بدون تخصص محدد'}</p><p>لغة الشرح: {state.profile.studyLanguage==='ar'?'العربية':'English'}</p></section><section className="panel"><h3>المحركات</h3><div className="infra ok">GitHub: المصدر والبناء والنشر</div><div className="infra ok">Puter AI: شرح، اختبارات، ترجمة وOCR للمطبوع والخط اليدوي</div><div className="infra warn">Neon: قاعدة المشروع موجودة؛ المزامنة السحابية للحسابات هي المرحلة التالية</div><p className="muted">عند أول استخدام للذكاء أو OCR قد يطلب Puter تسجيل دخول/تفويض مرة واحدة.</p></section></div></section>}

function GlobalSearch({state,q,openCourse,openLens,close}:{state:AppState;q:string;openCourse:(c:Course)=>void;openLens:(m:Material)=>void;close:()=>void}){const term=q.toLowerCase();const courses=state.courses.filter(c=>c.name.toLowerCase().includes(term)).slice(0,5);const mats=state.materials.filter(m=>m.name.toLowerCase().includes(term)||m.text.toLowerCase().includes(term)).slice(0,8);return <div className="modal" onClick={close}><div className="lens" onClick={e=>e.stopPropagation()}><div className="section-head"><div><h3>نتائج البحث</h3><p>“{q}”</p></div><button className="icon" onClick={close}><X/></button></div><div className="artifact-list">{courses.map(c=><button key={c.id} onClick={()=>openCourse(c)}><BookOpen/><div><b>{c.name}</b><small>مادة</small></div></button>)}{mats.map(m=><button key={m.id} onClick={()=>{openLens(m);close()}}><FileText/><div><b>{m.name}</b><small>مصدر</small></div></button>)}</div>{!courses.length&&!mats.length&&<Empty title="ما لقيت نتيجة" icon={Search}/>}</div></div>}
function SourceLens({material,onClose}:{material:Material;onClose:()=>void}){return <div className="modal" onClick={onClose}><div className="lens" onClick={e=>e.stopPropagation()}><div className="section-head"><div><h3>{material.name}</h3><p>{material.pages} صفحة • {humanSize(material.size)}</p></div><button className="icon" onClick={onClose}><X/></button></div>{material.error&&<div className="warning"><CircleAlert/>{material.error}</div>}<pre className="source-text">{material.text||'لا يوجد نص مستخرج.'}</pre><div className="lens-note">هذا النص هو ما يفهمه ScholarMCP. إذا كان المصدر صورة أو خطًا يدويًا فهو ناتج OCR؛ راجعه سريعًا إذا كانت الصورة غير واضحة.</div></div></div>}
function ArtifactModal({art,onClose}:{art:Artifact;onClose:()=>void}){const d:any=art.data||{};return <div className="modal" onClick={onClose}><div className="lens artifact-modal" onClick={e=>e.stopPropagation()}><div className="section-head"><div><h3>{art.title}</h3><span className={`truth ${art.truth}`}>{art.truth}</span></div><button className="icon" onClick={onClose}><X/></button></div>{art.type==='summary'&&<div className="summary-view"><p style={{whiteSpace:'pre-wrap'}}>{d.summary}</p><div className="chips">{(d.keyConcepts||[]).map((x:any,i:number)=><span key={i}>{x.title}</span>)}</div><b>تغطية تقديرية: {d.estimatedCoverage||art.coverage||'—'}%</b></div>}{art.type==='translation'&&<pre className="source-text">{d.text}</pre>}{art.type==='mindmap'&&<div className="mindmap"><div className="root">{d.nodes?.[0]?.label||'المادة'}</div><div className="branches">{(d.nodes||[]).slice(1).map((n:any)=><div key={n.id}><b>{n.label}</b><p>{n.definition}</p><small>{n.sourceRef}</small></div>)}</div></div>}{art.type==='package'&&<div className="package-view"><p>{d.summary}</p><div className="export-inline"><button className="ghost" onClick={()=>exportDocx(art.title,d.summary||'')}><Download/> Word</button><button className="ghost" onClick={()=>exportPptx({title:art.title,slides:d.slides||[]})}><Presentation/> PowerPoint</button></div><div className="slides-preview">{(d.slides||[]).map((s:any,i:number)=><div key={i}><b>{s.title}</b>{s.bullets?.map((x:string,j:number)=><p key={j}>• {x}</p>)}</div>)}</div></div>}</div></div>}
function FlashcardsModal({cards,onClose}:{cards:Flashcard[];onClose:()=>void}){const [i,setI]=useState(0);const [show,setShow]=useState(false);const due=cards.filter(c=>new Date(c.dueAt).getTime()<=Date.now());const list=due.length?due:cards;const c=list[i%Math.max(1,list.length)];function rate(good:boolean){if(!c)return;repo.reviewCard(c.id,good);setShow(false);setI(v=>v+1)}return <div className="modal"><div className="quiz-modal"><div className="section-head"><div><h3>بطاقات المراجعة</h3><p>{list.length?`${(i%list.length)+1} من ${list.length}`:'لا توجد بطاقات'}</p></div><button className="icon" onClick={onClose}><X/></button></div>{c?<><div className="question"><h3>{c.front}</h3><small>{c.sourceRef}</small></div>{show?<div className="explain"><p>{c.back}</p></div>:<button className="ghost wide" onClick={()=>setShow(true)}><Eye/> أظهر الجواب</button>}{show&&<div className="export-inline"><button className="danger" onClick={()=>rate(false)}><RefreshCw/> ما حفظتها</button><button className="primary" onClick={()=>rate(true)}><ThumbsUp/> أعرفها</button></div>}</>:<Empty title="أنشئ بطاقات من المادة أولًا" icon={Layers3}/>}</div></div>}
function QuizModal({course,questions,onClose,notify}:{course:Course;questions:any[];onClose:()=>void;notify:(m:string)=>void}){const [i,setI]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});const [done,setDone]=useState(false);const q=questions[i];const score=questions.filter((x,j)=>answers[j]===x.answerIndex).length;function finish(){questions.forEach((x,j)=>repo.recordTopic(course.id,x.topic,answers[j]===x.answerIndex));setDone(true);notify('تم تحديث نقاط الضعف حسب الاختبار')}return <div className="modal"><div className="quiz-modal"><div className="section-head"><div><h3>{done?'نتيجة الاختبار':`سؤال ${i+1} من ${questions.length}`}</h3></div><button className="icon" onClick={onClose}><X/></button></div>{done?<><div className="score-ring"><span>{score}/{questions.length}</span></div><p>النتيجة دخلت في Mastery للمفاهيم حتى تتغير جلساتك القادمة.</p><button className="primary wide" onClick={onClose}>إنهاء</button></>:<><div className="question"><h3>{q.question}</h3><small>{q.sourceRef}</small></div><div className="options">{q.choices.map((x:string,j:number)=><button key={j} className={answers[i]===j?'picked':''} onClick={()=>setAnswers(a=>({...a,[i]:j}))}>{x}</button>)}</div>{answers[i]!==undefined&&<div className="explain">{answers[i]===q.answerIndex?<><ThumbsUp/> صحيح</>:<>الإجابة الصحيحة: {q.choices[q.answerIndex]}</>}<p>{q.explanation}</p></div>}<button className="primary wide" disabled={answers[i]===undefined} onClick={()=>i===questions.length-1?finish():setI(i+1)}>{i===questions.length-1?'أظهر النتيجة':'التالي'}</button></>}</div></div>}
function Empty({title,text,icon:Icon,action,actionLabel}:{title:string;text?:string;icon:ComponentType;action?:()=>void;actionLabel?:string}){return <div className="empty"><Icon/><h3>{title}</h3>{text&&<p>{text}</p>}{action&&<button className="primary" onClick={action}>{actionLabel}</button>}</div>}
