type AnyObj=Record<string,any>;
const MODEL='gemini-3.8-flash';
function puter(){const p=(globalThis as any).puter;if(!p?.ai?.chat)throw new Error('محرك الذكاء السحابي غير جاهز. أعد تحميل الصفحة.');return p}
function txt(r:any){const v=r?.message?.content??r?.text??r;if(typeof v==='string')return v.replace(/<think>[\\s\\S]*?<\\/think>/gi,'').replace(/^\\s*```(?:json)?\\s*/i,'').replace(/\\s*```\\s*$/,'').trim();if(Array.isArray(v))return v.map((x:any)=>x?.text??'').join('');return JSON.stringify(v??'')}
function json(s:string){const t=txt(s);try{return JSON.parse(t)}catch{}const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}throw new Error('النموذج السحابي رجّع نتيجة غير منظمة. أعد المحاولة.')}
function blocks(raw:string){const out:any[]=[];let source='المصدر',page=1,buf:string[]=[];const flush=()=>{const t=buf.join('\\n').trim();if(t)out.push({source,page,text:t});buf=[]};for(const line of raw.split(/\\r?\\n/)){const s=line.match(/^SOURCE\\s+(.+)$/i);if(s){flush();source=s[1].trim();continue}const p=line.match(/^\\[\\[PAGE\\s+(\\d+)\\]\\]$/i);if(p){flush();page=Number(p[1]);continue}buf.push(line)}flush();return out}
function context(raw:string,action:string,p:any){const bs=blocks(raw);if(!bs.length)return raw.slice(0,60000);const q=String(p.question||p.prompt||p.topic||p.instructions||'').toLowerCase();const words=q.match(/[\\p{L}\\p{N}]{3,}/gu)||[];const score=(b:any)=>words.reduce((n,w)=>n+(b.text.toLowerCase().includes(w)?2:0),0);const picked=(action==='chat'||action==='custom'||action==='assignment')?bs.map(b=>({...b,s:score(b)})).sort((a,b)=>b.s-a.s).slice(0,14):bs.length>18?[...Array(18)].map((_,i)=>bs[Math.round(i*(bs.length-1)/17)]):bs;return picked.map((b:any)=>'[[SOURCE '+b.source+']] [[PAGE '+b.page+']]\\n'+b.text).join('\\n\\n').slice(0,60000)}
const BASE='أنت Scholar AI السحابي داخل ScholarMCP. اعتمد على المصدر المرفوع فقط في المهام source-grounded. لا تخترع مراجع أو صفحات أو بيانات. كل استشهاد يجب أن يشير إلى اسم المصدر ورقم الصفحة الموجودين في السياق. لا تعتبر SOURCE أو PAGE أو أسماء الملفات مفاهيم علمية. اكتب بالعربية الواضحة وحافظ على المصطلحات العلمية. عند طلب JSON أعد JSON صالحاً فقط بلا markdown.';
function instruction(a:string,p:AnyObj){switch(a){case'chat':return 'سؤال الطالب: '+(p.question||'')+'\\nأجب من المصدر وأعد {"text":"","truth":"supported|unverified","sourceRefs":[]}. ';case'summary':return 'أنشئ ملخصاً شاملاً. أعد {"summary":"","keyConcepts":[{"title":"","definition":"","sourceRef":""}],"estimatedCoverage":0,"omitted":[],"examRisk":[]} واستخرج 8-15 مفهوماً.';case'flashcards':return 'أنشئ '+(p.count||12)+' بطاقات. أعد {"cards":[{"front":"","back":"","topic":"","sourceRef":""}]}.';case'quiz':return 'أنشئ '+(p.count||10)+' أسئلة MCQ متنوعة. أعد {"questions":[{"question":"","choices":["","","",""],"answerIndex":0,"explanation":"","sourceRef":"","topic":"","difficulty":"easy|medium|hard"}]}.';case'mindmap':return 'أنشئ خريطة معرفة 8-20 عقدة. أعد {"nodes":[{"id":"root","label":"","definition":"","sourceRef":"","parent":null}]}.';case'study':return 'أنشئ جلسة دراسة عملية من 5-7 خطوات، الامتحان بعد '+(p.daysToExam??'غير محدد')+' يوم، والضعف: '+((p.weakTopics||[]).join('، ')||'غير معروف')+'. أعد JSON بخطوات.';case'assignment':return 'حلل الواجب والتعليمات والـRubric وأعد checklist وoutline وdraft وassessment.';case'package':return 'أنشئ حزمة أكاديمية عن '+(p.topic||'المادة')+' مع ملخص ومخطط وشرائح ومراجع.';default:return String(p.prompt||'نفذ المهمة الأكاديمية المطلوبة.')}}
async function ask(messages:any[],o:AnyObj={}){return puter().ai.chat(messages,{model:o.model||MODEL,temperature:o.temperature??0.15,max_tokens:o.max_tokens||1800,normalize:true})}
export async function smartTask(action:string,payload:AnyObj){const raw=String(payload?.context||'');if(action==='translate'){const bs=blocks(raw),target=payload?.target||'العربية',pieces:string[]=[];for(const b of bs.length?bs:[{source:'المصدر',page:1,text:raw}])for(let i=0;i<b.text.length;i+=9000){const r=await ask([{role:'system',content:'ترجم أكاديمياً إلى '+target+' بلا تلخيص، وحافظ على المصطلحات.'},{role:'user',content:b.text.slice(i,i+9000)}],{max_tokens:2600});pieces.push('SOURCE '+b.source+'\\n[[PAGE '+b.page+']]\\n'+txt(r))}return{text:pieces.join('\\n\\n'),complete:true}}const r=await ask([{role:'system',content:BASE},{role:'user',content:instruction(action,payload)+'\\n\\n--- المصدر ---\\n'+context(raw,action,payload)+'\\n--- نهاية المصدر ---'}],{max_tokens:action==='summary'||action==='package'||action==='custom'?2400:1600});return json(txt(r))}
export async function customTask(prompt:string,contextText=''){return smartTask('custom',{prompt,context:contextText})}
export async function ocrSource(source:File|Blob|string){const r=await puter().ai.img2txt(source,{provider:'mistral'});return String(r?.text??r??'').trim()}
export async function structuredOCR(source:File|Blob|string){return{text:await ocrSource(source),provider:'puter-cloud-mistral',handwriting:true,local:false}}
export async function handwrittenOCR(source:File|Blob|string){return ocrSource(source)}
export function ocrCapabilities(){return{mode:'cloud',printed:true,handwritten:true,multilingual:true,deviceCompute:false}}
export async function speechToText(source:File|Blob|string,_options:AnyObj={}){return puter().ai.speech2txt(source,{provider:'openai',model:'gpt-4o-mini-transcribe',response_format:'verbose_json',language:'ar'})}
export async function textToSpeech(text:string,o:AnyObj={}){return puter().ai.txt2speech(text.slice(0,3000),{provider:o.provider||'gemini',model:o.model||'gemini-3.8-flash-tts',language:o.lang||'ar'})}
export async function generateStudyImage(prompt:string,o:AnyObj={}){return puter().ai.txt2img(prompt,{model:o.model||'gemini-3.1-flash-image',aspect_ratio:o.aspectRatio||'16:9'})}
export async function generateStudyVideo(_prompt:string,_options:AnyObj={}){throw new Error('فيديو الدراسة يستخدم Cloud Video Worker.')} 
export async function localAIStatus(){return{cloud:true,local:false,model:MODEL,provider:'puter',deviceCompute:false}}
export async function resetLocalAI(){} export async function disposeLocalAI(){} export async function disposeOCR(){} export function aiAvailable(){return Boolean((globalThis as any).puter?.ai)}