import {useRef,useState} from 'react';
import {BarChart3,Brain,FileQuestion,LoaderCircle,Save,Sparkles,Upload} from 'lucide-react';
import {type AppState,LocalRepository,parseFile} from './lib';
import {analyzeExamDNA} from './academic-ai';
import './exam-dna.css';

const repo=new LocalRepository();
type Props={state:AppState;notify:(message:string)=>void};
export default function ExamDNAStudio({state,notify}:Props){
 const input=useRef<HTMLInputElement>(null);const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [dna,setDna]=useState<any>(null);const [saved,setSaved]=useState(false);
 async function run(list:File[]){if(!list.length)return;setFiles(list);setBusy(true);setDna(null);setSaved(false);try{let joined='';for(const f of list){const p=await parseFile(f);if(p.text.trim())joined+=`\n\nEXAM ${f.name}\n${p.text}`}if(joined.trim().length<80)throw new Error('ما قدرت أقرأ نص كافي من الامتحانات.');const d=await analyzeExamDNA(joined);setDna(d);notify('حللت نمط الامتحانات السابقة بدون ادعاء توقع الأسئلة')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function save(){if(!dna||!courseId)return;repo.addArtifact({courseId,type:'exam-dna',title:'بصمة الامتحان',truth:'inferred',data:dna});for(const t of dna.repeatedTopics||[])repo.upsertTopics(courseId,[{title:t.topic,sourceRef:'امتحانات سابقة'}]);setSaved(true);notify('حفظت بصمة الامتحان داخل المادة')}
 return <div className="exam-dna"><div className="panel"><div className="section-head"><div><span className="eyebrow">EXAM DNA</span><h3>افهم أسلوب الدكتور، لا تتنبأ بالغيب</h3><p>ارفع امتحانات سابقة حتى نعرف شنو يكرر، شلون يصيغ، ومستوى التفكير المطلوب.</p></div><FileQuestion/></div><div className="dna-inputs"><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input ref={input} hidden type="file" multiple accept=".pdf,.docx,.pptx,.txt,.md,.jpg,.jpeg,.png,.webp,image/*" onChange={e=>run([...(e.target.files||[])])}/><button className="primary" onClick={()=>input.current?.click()} disabled={busy||!state.courses.length}>{busy?<LoaderCircle className="spin"/>:<Upload/>} ارفع امتحانات سابقة</button></div>{files.length>0&&<p className="muted">{files.length} ملفات: {files.map(f=>f.name).join('، ')}</p>}</div>
 {dna&&<><div className="dna-grid"><div className="panel"><h4>أنواع الأسئلة</h4><div className="dna-bars">{(dna.questionTypes||[]).map((x:any,i:number)=><div key={i}><span>{x.type}</span><div><i style={{width:`${Math.min(100,Number(x.share)||0)}%`}}/></div><b>{x.share}%</b></div>)}</div></div><div className="panel"><h4>المواضيع المتكررة</h4><div className="dna-topics">{(dna.repeatedTopics||[]).map((x:any,i:number)=><span key={i}>{x.topic}<b>×{x.frequency}</b></span>)}</div></div><div className="panel"><h4>مستوى الامتحان</h4><div className="difficulty"><Brain/><b>{dna.difficulty||'mixed'}</b></div><p>{(dna.skills||[]).join(' • ')}</p></div></div><div className="panel"><div className="section-head"><div><h4>كيف تتهيأ لهذا النمط</h4><p>هاي توصيات مبنية على الامتحانات المرفوعة، مو تنبؤ بأسئلة جاية.</p></div><BarChart3/></div><ol className="dna-notes">{(dna.recommendations||[]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ol>{(dna.styleNotes||[]).length>0&&<div className="style-notes"><b>ملاحظات الصياغة</b>{dna.styleNotes.map((x:string,i:number)=><p key={i}>• {x}</p>)}</div>}<button className="primary" onClick={save} disabled={saved||!courseId}>{saved?<Save/>:<Sparkles/>} {saved?'محفوظ بالمادة':'احفظ البصمة'}</button></div></>}
 </div>
}
