import {useMemo,useState} from 'react';
import {BookOpenCheck,CheckCircle2,ClipboardCheck,FileSearch,LibraryBig,LoaderCircle,Quote,Search,ShieldAlert,Sparkles} from 'lucide-react';
import {type AppState,retrieve} from './lib';
import {customTask} from './puter';
import {scholarSearch,type ScholarPaper} from './research';
import './research-workbench.css';

type Props={state:AppState;notify:(message:string)=>void};
type Style='APA 7'|'MLA 9'|'Chicago'|'Harvard'|'Vancouver';
const styles:Style[]=['APA 7','MLA 9','Chicago','Harvard','Vancouver'];
function initials(authors:string[]){return authors.length?authors.join(', '):'Unknown author'}
function cite(p:ScholarPaper,style:Style,index=1){const a=initials(p.authors),y=p.year||'n.d.',t=p.title,j=p.journal||'';if(style==='MLA 9')return `${a}. “${t}.” ${j}${p.year?`, ${p.year}`:''}${p.doi?`, doi:${p.doi}`:''}.`;if(style==='Chicago')return `${a}. “${t}.” ${j} (${y}).${p.doi?` https://doi.org/${p.doi}`:''}`;if(style==='Harvard')return `${a} (${y}) ‘${t}’, ${j}.${p.doi?` doi:${p.doi}`:''}`;if(style==='Vancouver')return `${index}. ${a}. ${t}. ${j}. ${y}.${p.doi?` doi:${p.doi}`:''}`;return `${a} (${y}). ${t}. ${j}.${p.doi?` https://doi.org/${p.doi}`:''}`}

export default function ResearchWorkbench({state,notify}:Props){
 const [tab,setTab]=useState<'discover'|'claim'|'review'|'integrity'>('discover');
 return <div className="research-workbench"><div className="research-tabs"><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}><Search/> اكتشاف ومراجع</button><button className={tab==='claim'?'active':''} onClick={()=>setTab('claim')}><BookOpenCheck/> تحقق الادعاء</button><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}><LibraryBig/> Literature Review</button><button className={tab==='integrity'?'active':''} onClick={()=>setTab('integrity')}><ShieldAlert/> Integrity Guard</button></div>{tab==='discover'&&<Discovery notify={notify}/>} {tab==='claim'&&<ClaimVerifier state={state} notify={notify}/>} {tab==='review'&&<LiteratureReview notify={notify}/>} {tab==='integrity'&&<IntegrityGuard state={state} notify={notify}/>}</div>
}

function Discovery({notify}:{notify:(x:string)=>void}){const [q,setQ]=useState('');const [rows,setRows]=useState<ScholarPaper[]>([]);const [busy,setBusy]=useState(false);const [style,setStyle]=useState<Style>('APA 7');const [selected,setSelected]=useState<Record<string,boolean>>({});async function run(){if(!q.trim())return;setBusy(true);try{setRows(await scholarSearch(q.trim()))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}const picked=rows.filter(x=>selected[x.id]);return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">ACADEMIC DISCOVERY</span><h3>ابحث وخذ المرجع بدون ما تطلع من ScholarMCP</h3><p>Crossref وOpenAlex يجيبون البيانات؛ النتائج والمراجع تبقى هنا.</p></div><FileSearch/></div><div className="research-query"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="forensic toxicology biomarkers"/><button className="primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Search/>} بحث</button></div></div>{rows.length>0&&<><div className="paper-browser">{rows.map(p=><article className={selected[p.id]?'selected':''} key={p.id}><label><input type="checkbox" checked={!!selected[p.id]} onChange={e=>setSelected(x=>({...x,[p.id]:e.target.checked}))}/><span/></label><div><h4>{p.title}</h4><p>{p.authors.slice(0,4).join('، ')||'—'} • {p.year||'—'} • {p.journal||p.source}</p>{p.abstract&&<details><summary>الملخص</summary><p>{p.abstract}</p></details>}<small>{p.citations??0} استشهاد {p.openAccess?'• وصول مفتوح':''} {p.doi?`• DOI ${p.doi}`:''}</small></div></article>)}</div><div className="panel citation-box"><div className="section-head"><div><h3>Citation Builder</h3><p>{picked.length} مصدر محدد</p></div><select value={style} onChange={e=>setStyle(e.target.value as Style)}>{styles.map(x=><option key={x}>{x}</option>)}</select></div>{picked.length?picked.map((p,i)=><div className="citation-line" key={p.id}><Quote/><p>{cite(p,style,i+1)}</p><button className="ghost compact" onClick={()=>navigator.clipboard.writeText(cite(p,style,i+1)).then(()=>notify('نسخت المرجع'))}>نسخ</button></div>):<p className="muted">حدد مصادر من النتائج حتى أبني المراجع.</p>}</div></>}</div>}

function ClaimVerifier({state,notify}:Props){const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [claim,setClaim]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);const mats=state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim());async function run(){if(!claim.trim()||!mats.length){notify('اكتب الادعاء واختَر مادة بيها مصادر');return}setBusy(true);try{const hits=retrieve(mats,claim,12);const context=hits.map(h=>`SOURCE ${h.material}\n[[PAGE ${h.page}]]\n${h.text}`).join('\n\n');const r:any=await customTask(`تحقق من الادعاء التالي اعتماداً على المصدر فقط: «${claim}». لا تبحث خارج المصدر ولا تخمن. صنفه supported أو partial أو unsupported أو contradicted. أعد JSON: {"status":"supported|partial|unsupported|contradicted","confidence":0,"explanation":"","evidence":[{"quote":"إعادة صياغة قصيرة للدليل، لا تنسخ فقرة طويلة","sourceRef":"اسم الملف — ص N"}],"missing":""}.`,context);setResult(r)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">CLAIM VERIFICATION</span><h3>هل هذا الادعاء موجود فعلًا بمصادري؟</h3></div><BookOpenCheck/></div><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea rows={5} value={claim} onChange={e=>setClaim(e.target.value)} placeholder="اكتب الجملة أو الادعاء الذي تريد التحقق منه…"/><button className="primary" disabled={busy} onClick={run}>{busy?<LoaderCircle className="spin"/>:<CheckCircle2/>} تحقق من المصدر</button></div>{result&&<div className={`panel claim-result ${result.status||'unsupported'}`}><div className="claim-score"><b>{String(result.status||'unsupported')}</b><span>{Math.max(0,Math.min(100,Number(result.confidence)||0))}%</span></div><p>{result.explanation}</p>{(result.evidence||[]).map((x:any,i:number)=><div className="evidence-row" key={i}><Quote/><div><p>{x.quote}</p><small>{x.sourceRef}</small></div></div>)}{result.missing&&<div className="warning">{result.missing}</div>}</div>}</div>}

function LiteratureReview({notify}:{notify:(x:string)=>void}){const [q,setQ]=useState('');const [papers,setPapers]=useState<ScholarPaper[]>([]);const [selected,setSelected]=useState<Record<string,boolean>>({});const [busy,setBusy]=useState('');const [review,setReview]=useState<any>(null);async function search(){if(!q.trim())return;setBusy('search');try{setPapers(await scholarSearch(q.trim()))}catch(e){notify((e as Error).message)}finally{setBusy('')}}async function synthesize(){const picked=papers.filter(p=>selected[p.id]).slice(0,12);if(picked.length<2){notify('حدد مصدرين على الأقل');return}setBusy('review');try{const corpus=picked.map((p,i)=>`PAPER ${i+1}\nTitle: ${p.title}\nAuthors: ${p.authors.join(', ')}\nYear: ${p.year||''}\nJournal: ${p.journal||''}\nDOI: ${p.doi||''}\nAbstract: ${p.abstract||'No abstract available'}`).join('\n\n');const r:any=await customTask(`ابن Literature Review من بيانات الأوراق التالية فقط. لا تدّعِ أنك قرأت النص الكامل إذا الموجود Abstract فقط. أعد JSON: {"synthesis":"","themes":[{"theme":"","papers":[1],"finding":""}],"agreements":[""],"disagreements":[""],"gaps":[""],"limitations":[""],"nextQuestions":[""]}.`,corpus);setReview(r)}catch(e){notify((e as Error).message)}finally{setBusy('')}}return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">LITERATURE REVIEW</span><h3>من أوراق متفرقة إلى صورة بحثية واحدة</h3><p>يصرّح بحدوده: Abstract مو Full Text.</p></div><LibraryBig/></div><div className="research-query"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="موضوع المراجعة…"/><button className="ghost" onClick={search}>{busy==='search'?<LoaderCircle className="spin"/>:<Search/>} ابحث</button><button className="primary" onClick={synthesize} disabled={busy==='review'}>{busy==='review'?<LoaderCircle className="spin"/>:<Sparkles/>} حلّل المحدد</button></div></div>{papers.length>0&&<div className="paper-pick-grid">{papers.map((p,i)=><label key={p.id} className={selected[p.id]?'picked':''}><input type="checkbox" checked={!!selected[p.id]} onChange={e=>setSelected(x=>({...x,[p.id]:e.target.checked}))}/><b>{i+1}. {p.title}</b><small>{p.year||'—'} • {p.journal||p.source}</small></label>)}</div>}{review&&<div className="review-grid"><div className="panel span2"><h3>الخلاصة المركبة</h3><p>{review.synthesis}</p></div><ReviewList title="الثيمات" rows={(review.themes||[]).map((x:any)=>`${x.theme}: ${x.finding}`)}/><ReviewList title="الفجوات" rows={review.gaps||[]}/><ReviewList title="نقاط الاتفاق" rows={review.agreements||[]}/><ReviewList title="الاختلافات" rows={review.disagreements||[]}/><ReviewList title="الحدود" rows={review.limitations||[]}/><ReviewList title="أسئلة تالية" rows={review.nextQuestions||[]}/></div>}</div>}

function IntegrityGuard({state,notify}:Props){const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [draft,setDraft]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);const mats=state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim());async function run(){if(!draft.trim()||!mats.length){notify('الصق المسودة واختَر مادة بيها مصادر');return}setBusy(true);try{const context=mats.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n').slice(0,100000);const r:any=await customTask(`أنت Integrity Guard. افحص المسودة التالية مقابل مصادر الطالب فقط. لا تدّعِ كشف سرقة أدبية من الإنترنت؛ وظيفتك: ادعاءات بلا دعم، استشهادات ناقصة، اقتباس طويل أو صياغة قريبة جدًا من المصدر، ومراجع مخترعة. أعد JSON: {"score":0,"unsupported":[{"text":"","reason":"","sourceRef":""}],"citationIssues":[""],"closeParaphrase":[{"text":"","suggestion":""}],"inventedReferences":[""],"safe":[""],"verdict":""}.\nالمسودة:\n${draft.slice(0,60000)}`,context);setResult(r)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">INTEGRITY GUARD</span><h3>دقّق قبل التسليم</h3><p>ما يسوي مسرحية “كاشف سرقة 99%”؛ يفحص ما نقدر نثبته من مصادرك.</p></div><ClipboardCheck/></div><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea rows={12} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="الصق البحث أو الواجب هنا…"/><button className="primary" onClick={run} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<ShieldAlert/>} افحص النزاهة</button></div>{result&&<div className="integrity-report"><div className="integrity-score"><b>{Math.max(0,Math.min(100,Number(result.score)||0))}</b><span>/100</span><p>{result.verdict}</p></div><ReviewList title="ادعاءات تحتاج دعم" rows={(result.unsupported||[]).map((x:any)=>`${x.text} — ${x.reason}${x.sourceRef?` (${x.sourceRef})`:''}`)}/><ReviewList title="مشاكل الاستشهاد" rows={result.citationIssues||[]}/><ReviewList title="صياغة قريبة من المصدر" rows={(result.closeParaphrase||[]).map((x:any)=>`${x.text} → ${x.suggestion}`)}/><ReviewList title="مراجع مشتبه باختلاقها" rows={result.inventedReferences||[]}/><ReviewList title="أجزاء سليمة" rows={result.safe||[]}/></div>}</div>}
function ReviewList({title,rows}:{title:string;rows:string[]}){return <div className="panel review-list"><h4>{title}</h4>{rows.length?rows.map((x,i)=><p key={i}>• {x}</p>):<p className="muted">لا توجد ملاحظات واضحة.</p>}</div>}
