import {useMemo,useState} from 'react';
import {Brain,Download,FileText,LoaderCircle,MessageCircleQuestion,Presentation,Sparkles} from 'lucide-react';
import {type AppState,aiTask,exportDocx,exportPptx,LocalRepository} from './lib';
import {buildSeminarRehearsal} from './academic-ai';

const repo=new LocalRepository();
type Props={state:AppState;notify:(message:string)=>void};
export default function SeminarStudio({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [title,setTitle]=useState('');const [busy,setBusy]=useState('');const [pack,setPack]=useState<any>(null);const [coach,setCoach]=useState<any>(null);
 const course=state.courses.find(c=>c.id===courseId);const mats=useMemo(()=>state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim()),[state.materials,courseId]);
 async function generate(){if(!course||!mats.length){notify('اختَر مادة بيها مصدر جاهز أولاً');return}setBusy('generate');setCoach(null);try{const context=mats.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n');const d:any=await aiTask('package',{context,topic:title.trim()||course.name});setPack(d);repo.addArtifact({courseId,type:'package',title:`سيمنار — ${d.title||title||course.name}`,truth:'supported',data:d});notify('جهزت السيمنار والشرائح وملاحظات الإلقاء')}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 async function rehearse(){if(!pack)return;setBusy('coach');try{const d=await buildSeminarRehearsal(pack.title||title,pack.slides||[]);setCoach(d);notify('جهزت أسئلة المناقشة وخطة الدفاع عن السيمنار')}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 const docBody=pack?`${pack.summary||''}\n\n${(pack.slides||[]).map((s:any,i:number)=>`الشريحة ${i+1}: ${s.title}\n${(s.bullets||[]).join('\n')}\nملاحظات المتحدث: ${s.notes||''}`).join('\n\n')}`:'';
 return <div className="seminar-studio"><div className="panel"><div className="section-head"><div><span className="eyebrow">SEMINAR STUDIO</span><h3>من المادة إلى سيمنار قابل للتعديل</h3><p>شرائح + Speaker Notes + نسخة Word + تدريب على أسئلة المدرس.</p></div><Presentation/></div>{!state.courses.length?<p className="muted">أضف مادة وارفع مصدر أولاً.</p>:<div className="seminar-form"><select value={courseId} onChange={e=>{setCourseId(e.target.value);setPack(null);setCoach(null)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`عنوان السيمنار — الافتراضي: ${course?.name||''}`}/><button className="primary" onClick={generate} disabled={!!busy||!mats.length}>{busy==='generate'?<LoaderCircle className="spin"/>:<Sparkles/>} ابنِ السيمنار</button></div>}<small className="muted">المصادر الجاهزة: {mats.length}</small></div>
 {pack&&<><div className="panel"><div className="section-head"><div><h3>{pack.title||title||course?.name}</h3><p>{pack.summary}</p></div><div className="export-inline"><button className="ghost" onClick={()=>exportDocx(pack.title||'Seminar',docBody)}><FileText/> Word</button><button className="primary" onClick={()=>exportPptx({title:pack.title||'Seminar',slides:pack.slides||[]})}><Download/> PowerPoint</button></div></div><div className="seminar-slides">{(pack.slides||[]).map((s:any,i:number)=><article key={i}><span>{i+1}</span><div><h4>{s.title}</h4>{(s.bullets||[]).map((b:string,j:number)=><p key={j}>• {b}</p>)}{s.notes&&<details><summary>ملاحظات المتحدث</summary><p>{s.notes}</p></details>}</div></article>)}</div><button className="ghost wide" onClick={rehearse} disabled={!!busy}>{busy==='coach'?<LoaderCircle className="spin"/>:<MessageCircleQuestion/>} جهزني للمناقشة</button></div>{coach&&<div className="panel"><div className="section-head"><div><h3>الدفاع عن السيمنار</h3><p>ابدأ بهدوء، جاوب من محتوى عرضك، ولا تحاول تتفلسف خارج المصدر 😅</p></div><Brain/></div>{coach.opening&&<div className="coach-script"><b>افتتاحية مقترحة</b><p>{coach.opening}</p></div>}<div className="coach-questions">{(coach.questions||[]).map((q:any,i:number)=><article key={i}><b>س{i+1}. {q.question}</b><p>{q.answer}</p><small>مرتبط بالشريحة {q.slide||'—'}</small></article>)}</div>{(coach.deliveryTips||[]).length>0&&<div className="tips"><b>انتبه:</b><ul>{coach.deliveryTips.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>}</div>}</>}
 </div>
}
