import {useMemo,useState} from 'react';
import {Brain,Check,ChevronDown,Flame,LoaderCircle,RefreshCw,Sparkles,X} from 'lucide-react';
import {type AppState,aiTask,LocalRepository} from './lib';
import {review as reviewFSRS,type ScholarRating} from './spaced';
import './smart-feed.css';

const repo=new LocalRepository();
type Props={state:AppState;notify:(message:string)=>void};
export default function SmartFeed({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [busy,setBusy]=useState(false);const [index,setIndex]=useState(0);const [show,setShow]=useState(false);const [session,setSession]=useState({done:0,good:0});
 const course=state.courses.find(c=>c.id===courseId);const cards=useMemo(()=>state.flashcards.filter(c=>c.courseId===courseId).slice().sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)),[state.flashcards,courseId]);const mats=state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim());const card=cards.length?cards[index%cards.length]:null;
 async function build(){if(!mats.length){notify('ارفع مصدر للمادة أولاً');return}setBusy(true);try{const context=mats.map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n');const r:any=await aiTask('flashcards',{context,count:24});repo.addFlashcards(courseId,r.cards||[]);setIndex(0);setShow(false);notify(`جهزت ${(r.cards||[]).length} لقطة دراسة من مادتك`)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function rate(r:ScholarRating){if(!card)return;const next=reviewFSRS(card,r);const local=repo.state.flashcards.find(x=>x.id===card.id);if(local){local.dueAt=(next.due as Date).toISOString();local.interval=Math.max(0,Math.round((+new Date(local.dueAt)-Date.now())/86400000));repo.persist()}setSession(s=>({done:s.done+1,good:s.good+(r==='good'||r==='easy'?1:0)}));setShow(false);setIndex(i=>i+1)}
 return <div className="feed-shell"><div className="feed-top"><div><span className="eyebrow">SMART FEED</span><h3>سكرول يفيدك بدل ما ياكل وقتك</h3><p>الأولوية للمستحق ونقاط الضعف. كل بطاقة من ملفاتك.</p></div><div className="feed-streak"><Flame/><b>{session.done}</b><small>اليوم</small></div></div><div className="feed-controls"><select value={courseId} onChange={e=>{setCourseId(e.target.value);setIndex(0);setShow(false)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="ghost" onClick={build} disabled={busy||!courseId}>{busy?<LoaderCircle className="spin"/>:<RefreshCw/>} {cards.length?'جدّد التغذية':'أنشئ التغذية'}</button></div>{card?<div className="feed-card"><div className="feed-card-head"><span>{course?.name}</span><small>{index%cards.length+1} / {cards.length}</small></div><div className="feed-question"><Brain/><h2>{card.front}</h2>{card.sourceRef&&<small>{card.sourceRef}</small>}</div>{show?<div className="feed-answer"><b>الجواب</b><p>{card.back}</p></div>:<button className="reveal" onClick={()=>setShow(true)}><ChevronDown/> أظهر الجواب</button>}{show&&<div className="feed-rate"><button className="again" onClick={()=>rate('again')}><X/> ما أعرفها</button><button className="hard" onClick={()=>rate('hard')}>صعبة</button><button className="good" onClick={()=>rate('good')}><Check/> أعرفها</button></div>}<div className="feed-progress"><span style={{width:`${cards.length?((index%cards.length+1)/cards.length)*100:0}%`}}/></div></div>:<div className="panel feed-empty"><Sparkles/><h3>ما عندك Feed بعد</h3><p>اضغط «أنشئ التغذية» حتى أحول المادة إلى مراجعة سريعة تشبه السحب العمودي، بس بدل ضياع ساعتين تحصل مراجعة حقيقية.</p><button className="primary" onClick={build} disabled={busy||!mats.length}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>} أنشئ من المصدر</button></div>} {session.done>0&&<div className="feed-session"><b>{session.good}/{session.done}</b><span>إجابات قوية بهذه الجلسة</span></div>}</div>
}
