import {useEffect,useMemo,useRef,useState} from 'react';
import {Download,LoaderCircle,Pause,Play,Sparkles,Video} from 'lucide-react';
import {type AppState,retrieve,safeFileName} from './lib';
import {customTask} from './scholar-engine';
import './study-video.css';

type Props={state:AppState;notify:(message:string)=>void};
type Scene={title:string;narration:string;onScreen:string;visualHint:string};
type Story={title:string;hook:string;scenes:Scene[];closing:string};
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number){const words=text.split(/\s+/);let line='';let yy=y;for(const word of words){const test=`${line}${word} `;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,yy);line=`${word} `;yy+=lineHeight}else line=test}if(line)ctx.fillText(line.trim(),x,yy);return yy}

export default function StudyVideoStudio({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [topic,setTopic]=useState('');const [sceneCount,setSceneCount]=useState(6);const [busy,setBusy]=useState('');const [story,setStory]=useState<Story|null>(null);const [scene,setScene]=useState(0);const [playing,setPlaying]=useState(false);const canvas=useRef<HTMLCanvasElement>(null);
 const course=state.courses.find(c=>c.id===courseId);const mats=useMemo(()=>state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim()),[state.materials,courseId]);
 useEffect(()=>{if(!playing||!story)return;const current=story.scenes[scene];window.speechSynthesis?.cancel();if(current&&'speechSynthesis'in window){const u=new SpeechSynthesisUtterance(current.narration);u.lang=/[\u0600-\u06ff]/.test(current.narration)?'ar-IQ':'en-US';u.rate=.96;window.speechSynthesis.speak(u)}const t=setTimeout(()=>{if(scene>=story.scenes.length-1){setPlaying(false);window.speechSynthesis?.cancel()}else setScene(v=>v+1)},5200);return()=>clearTimeout(t)},[playing,scene,story]);
 async function build(){if(!course||!mats.length){notify('اختَر مادة بيها مصدر جاهز أولاً');return}setBusy('build');setStory(null);try{const query=topic.trim()||course.name;const hits=retrieve(mats,query,18);const context=hits.map(h=>`SOURCE ${h.material}\n[[PAGE ${h.page}]]\n${h.text}`).join('\n\n');const r:any=await customTask(`حوّل المادة إلى فيديو تعليمي قصير داخل ScholarMCP عن «${query}». الفيديو للطالب الجامعي ويجب أن يكون سريعاً وواضحاً، وكل معلومة من المصدر فقط. أنشئ ${sceneCount} مشاهد. لكل مشهد عنوان قصير، narration من جملتين أو ثلاث، نص مختصر يظهر على الشاشة، واقتراح بصري بسيط لا يحتاج صوراً خارجية. أعد JSON: {"title":"...","hook":"...","scenes":[{"title":"...","narration":"...","onScreen":"...","visualHint":"..."}],"closing":"..."}.`,context);const scenes:Array<Scene>=Array.isArray(r.scenes)?r.scenes.slice(0,sceneCount).map((x:any)=>({title:String(x.title||''),narration:String(x.narration||''),onScreen:String(x.onScreen||''),visualHint:String(x.visualHint||'')})):[];if(!scenes.length)throw new Error('تعذر بناء مشاهد الفيديو.');setStory({title:String(r.title||query),hook:String(r.hook||''),scenes,closing:String(r.closing||'')});setScene(0);notify('جهزت فيديو تعليمي من المصدر داخل ScholarMCP')}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 function toggle(){if(!story)return;if(playing){setPlaying(false);window.speechSynthesis?.cancel()}else setPlaying(true)}
 async function renderWebm(){if(!story||!canvas.current)return;const c=canvas.current;if(!('captureStream'in c)||typeof MediaRecorder==='undefined'){notify('تصدير WebM غير مدعوم بهذا المتصفح؛ التشغيل داخل المنصة يعمل طبيعي.');return}setBusy('render');try{const ctx=c.getContext('2d');if(!ctx)throw new Error('تعذر تشغيل محرر الفيديو.');const stream=c.captureStream(30);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2500000});const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise<void>(resolve=>{rec.onstop=()=>resolve()});rec.start(500);const seconds=4.2;for(let i=0;i<story.scenes.length;i++){const s=story.scenes[i];const started=performance.now();while((performance.now()-started)/1000<seconds){const p=Math.min(1,(performance.now()-started)/(seconds*1000));drawFrame(ctx,c,s,story.title,i,story.scenes.length,p);await new Promise(r=>requestAnimationFrame(()=>r(null)))}}rec.stop();await done;stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'video/webm'});download(blob,`${safeFileName(story.title)}-ScholarMCP.webm`);notify('نزل الفيديو WebM — نسخة مرئية مولدة من المادة')}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 const current=story?.scenes[scene];return <div className="study-video-studio"><div className="panel"><div className="section-head"><div><span className="eyebrow">AI STUDY VIDEO</span><h3>فيديو تعليمي من مادتك</h3><p>الذكاء يبني السيناريو من المصدر، والتشغيل والتصدير يصير داخل ScholarMCP.</p></div><Video/></div><div className="video-builder"><select value={courseId} onChange={e=>{setCourseId(e.target.value);setStory(null)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder={`الموضوع — مثل ${course?.name||'DNA'}`}/><select value={sceneCount} onChange={e=>setSceneCount(Number(e.target.value))}>{[5,6,7,8].map(n=><option key={n} value={n}>{n} مشاهد</option>)}</select><button className="primary" onClick={build} disabled={!!busy||!mats.length}>{busy==='build'?<LoaderCircle className="spin"/>:<Sparkles/>} إنشاء الفيديو</button></div><small>المصادر الجاهزة: {mats.length}</small></div>{story&&<div className="panel video-preview"><div className="section-head"><div><h3>{story.title}</h3><p>{story.hook}</p></div><div className="export-inline"><button className="primary" onClick={toggle}>{playing?<Pause/>:<Play/>} {playing?'إيقاف':'تشغيل'}</button><button className="ghost" onClick={renderWebm} disabled={!!busy}>{busy==='render'?<LoaderCircle className="spin"/>:<Download/>} WebM</button></div></div><div className="video-stage"><div className="stage-count">{scene+1}/{story.scenes.length}</div><span className="visual-hint">{current?.visualHint||'شرح بصري مبسط'}</span><h2>{current?.title}</h2><p>{current?.onScreen}</p><div className="narration">{current?.narration}</div><div className="stage-progress"><span style={{width:`${((scene+1)/story.scenes.length)*100}%`}}/></div></div><div className="scene-strip">{story.scenes.map((s,i)=><button className={scene===i?'active':''} key={i} onClick={()=>{setPlaying(false);setScene(i)}}><b>{i+1}</b><span>{s.title}</span></button>)}</div><canvas ref={canvas} width="1280" height="720" className="render-canvas"/></div>}</div>
}
function drawFrame(ctx:CanvasRenderingContext2D,c:HTMLCanvasElement,scene:Scene,title:string,index:number,total:number,progress:number){const g=ctx.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#071a35');g.addColorStop(1,'#174b91');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.textAlign='center';ctx.direction='rtl';ctx.fillStyle='#8ab4ff';ctx.font='700 28px Arial';ctx.fillText(title,c.width/2,75);ctx.fillStyle='#ffffff';ctx.font='800 58px Arial';wrap(ctx,scene.title,c.width/2,210,1000,70);ctx.fillStyle='#dbeafe';ctx.font='500 38px Arial';wrap(ctx,scene.onScreen,c.width/2,390,1000,54);ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(100,650,1080,10);ctx.fillStyle='#67e8f9';ctx.fillRect(100,650,1080*((index+progress)/total),10);ctx.fillStyle='#b8c9df';ctx.font='600 22px Arial';ctx.fillText(`${index+1} / ${total}`,c.width/2,695)}
