import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Brain,CheckCircle2,Clock,Download,FileCheck2,GitBranch,Languages,LoaderCircle,Mic,Play,RotateCcw,ShieldCheck,Square,Volume2} from 'lucide-react';
import {type AppState,LocalRepository,aiTask,courseMastery,exportDocx,retrieve,weakest} from './lib';
import {customTask,speechToText,textToSpeech} from './puter';
import './student-tools.css';

type Props={state:AppState;notify:(message:string)=>void};
const repo=new LocalRepository();
const readyFor=(state:AppState,courseId:string)=>state.materials.filter(m=>m.courseId===courseId&&m.status==='ready'&&m.text.trim());
const contextFor=(state:AppState,courseId:string)=>readyFor(state,courseId).map(m=>`SOURCE ${m.name}\n${m.text}`).join('\n\n');

export function TranslationStudio({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [target,setTarget]=useState('العربية');const [locks,setLocks]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);
 const course=state.courses.find(c=>c.id===courseId);const mats=readyFor(state,courseId);const locked=locks.split(/[,\n؛]/).map(x=>x.trim()).filter(Boolean);
 async function run(){if(!course||!mats.length){notify('اختَر مادة بيها مصدر جاهز أولًا');return}setBusy(true);setResult(null);try{const d:any=await aiTask('translate',{context:contextFor(state,courseId),target,glossaryLock:locked});setResult(d);repo.addArtifact({courseId,type:'translation-studio',title:`ترجمة ${course.name} — ${target}`,truth:'supported',data:{...d,target,glossaryLock:locked}});notify('اكتملت ترجمة المادة وحفظت نسخة داخل ScholarMCP')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">TRANSLATION STUDIO</span><h3>ترجمة كاملة + Glossary Lock</h3><p>ترجم كل المادة مع تثبيت المصطلحات التي ممنوع تتغير.</p></div><Languages/></div><div className="tool-form"><label>المادة<select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>لغة الإخراج<select value={target} onChange={e=>setTarget(e.target.value)}>{['العربية','English','Türkçe','Français','Deutsch','Español','فارسی'].map(x=><option key={x}>{x}</option>)}</select></label><label className="span2">مصطلحات مقفلة<textarea rows={3} value={locks} onChange={e=>setLocks(e.target.value)} placeholder="DNA, PCR, Chain of Custody… كل مصطلح بسطر أو افصله بفاصلة"/></label></div><div className="lock-preview"><ShieldCheck/> {locked.length?`${locked.length} مصطلح مقفول: ${locked.slice(0,8).join(' • ')}`:'ماكو Glossary Lock؛ المصطلحات العلمية تبقى حسب سياق المصدر.'}</div><button className="primary" disabled={busy||!mats.length} onClick={run}>{busy?<LoaderCircle className="spin"/>:<Languages/>} ترجم المادة كاملة</button></div>{result&&<div className="panel"><div className="section-head"><div><h3>النسخة المترجمة</h3><p>{target} • {mats.length} مصدر</p></div><button className="ghost" onClick={()=>exportDocx(`${course?.name||'ScholarMCP'}-${target}`,String(result.text||''))}><Download/> Word</button></div><pre className="translated-output">{result.text}</pre></div>}</div>
}

export function CoverageGuard({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [busy,setBusy]=useState(false);const [data,setData]=useState<any>(null);const course=state.courses.find(c=>c.id===courseId);const mats=readyFor(state,courseId);const artifacts=state.artifacts.filter(a=>a.courseId===courseId);
 async function run(){if(!course||!mats.length){notify('ارفع مصدرًا للمادة أولًا');return}setBusy(true);try{const context=contextFor(state,courseId);const outputs=artifacts.slice(0,20).map(a=>`${a.type}: ${a.title}\n${JSON.stringify(a.data).slice(0,2500)}`).join('\n\n');const r:any=await customTask(`أنت Coverage Guard داخل ScholarMCP. قارن المصدر الأصلي بالمخرجات الدراسية الحالية ولا تجامل. اكتشف المواضيع التي غطيناها والمواضيع التي قد تسقط من الملخصات أو الاختبارات. أعد JSON: {"coverage":0,"covered":[{"topic":"","sourceRef":"اسم الملف — ص N"}],"missing":[{"topic":"","reason":"","sourceRef":"اسم الملف — ص N"}],"examRisk":[""],"nextAction":""}. لا تعتبر أسماء الملفات مواضيع.\nالمخرجات الحالية:\n${outputs||'لا توجد مخرجات بعد.'}`,context);setData(r);repo.addArtifact({courseId,type:'coverage-guard',title:`Coverage Guard — ${course.name}`,truth:'supported',coverage:Number(r.coverage)||0,data:r});notify('اكتمل فحص التغطية')}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">COVERAGE GUARD</span><h3>شنو درسنا وشنو طاح من عدنا؟</h3><p>يقارن المصدر بالمخرجات بدل ما يعتبر الملخص كامل لأنه شكله مرتب.</p></div><FileCheck2/></div><div className="inline-controls"><select value={courseId} onChange={e=>{setCourseId(e.target.value);setData(null)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary" onClick={run} disabled={busy||!mats.length}>{busy?<LoaderCircle className="spin"/>:<ShieldCheck/>} افحص التغطية</button></div></div>{data&&<><div className="coverage-score"><b>{Math.max(0,Math.min(100,Number(data.coverage)||0))}%</b><div><span style={{width:`${Math.max(0,Math.min(100,Number(data.coverage)||0))}%`}}/></div><p>{data.nextAction||'راجع العناصر الناقصة قبل الامتحان.'}</p></div><div className="coverage-grid"><div className="panel"><h4>مغطى</h4>{(data.covered||[]).map((x:any,i:number)=><div className="coverage-item ok" key={i}><CheckCircle2/><div><b>{x.topic}</b><small>{x.sourceRef}</small></div></div>)}</div><div className="panel"><h4>ناقص / خطر</h4>{(data.missing||[]).map((x:any,i:number)=><div className="coverage-item miss" key={i}><ShieldCheck/><div><b>{x.topic}</b><p>{x.reason}</p><small>{x.sourceRef}</small></div></div>)}{(data.examRisk||[]).map((x:string,i:number)=><p className="risk-line" key={i}>• {x}</p>)}</div></div></>}</div>
}

export function ExamSimulator({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [count,setCount]=useState(20);const [minutes,setMinutes]=useState(25);const [busy,setBusy]=useState(false);const [questions,setQuestions]=useState<any[]>([]);const [answers,setAnswers]=useState<Record<number,number>>({});const [left,setLeft]=useState(0);const [done,setDone]=useState(false);const course=state.courses.find(c=>c.id===courseId);const mats=readyFor(state,courseId);
 useEffect(()=>{if(!questions.length||done||left<=0)return;const t=setInterval(()=>setLeft(x=>Math.max(0,x-1)),1000);return()=>clearInterval(t)},[questions.length,done,left]);
 useEffect(()=>{if(questions.length&&!done&&left===0)finish(true)},[left]);
 async function start(){if(!course||!mats.length){notify('المادة تحتاج مصدر جاهز أولًا');return}setBusy(true);setDone(false);setAnswers({});try{const r:any=await aiTask('quiz',{context:contextFor(state,courseId),count});const qs=(r.questions||[]).slice(0,count);if(!qs.length)throw new Error('تعذر بناء الامتحان.');setQuestions(qs);setLeft(minutes*60);notify(`بدأ امتحان ${qs.length} سؤال`)}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 function finish(auto=false){if(done||!questions.length)return;questions.forEach((q,i)=>repo.recordTopic(courseId,q.topic,answers[i]===q.answerIndex));setDone(true);if(auto)notify('انتهى الوقت وتم تسليم الامتحان تلقائيًا')}
 const score=questions.filter((q,i)=>answers[i]===q.answerIndex).length;const pct=questions.length?Math.round(score/questions.length*100):0;
 return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">EXAM SIMULATOR</span><h3>فاينل كامل بوقت حقيقي</h3><p>أسئلة من نفس المادة، مؤقت، نتيجة، وتحديث تلقائي لخريطة الضعف.</p></div><Clock/></div><div className="exam-config"><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label>الأسئلة<input type="number" min="5" max="40" value={count} onChange={e=>setCount(Math.max(5,Math.min(40,Number(e.target.value)||20)))}/></label><label>الدقائق<input type="number" min="5" max="120" value={minutes} onChange={e=>setMinutes(Math.max(5,Math.min(120,Number(e.target.value)||25)))}/></label><button className="primary" onClick={start} disabled={busy||!mats.length}>{busy?<LoaderCircle className="spin"/>:<Play/>} ابدأ امتحان جديد</button></div></div>{questions.length>0&&<div className="panel exam-paper"><div className="exam-head"><b>{course?.name}</b><span><Clock/> {Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span></div>{questions.map((q,i)=><article className="sim-question" key={i}><h4>{i+1}. {q.question}</h4><div>{(q.choices||[]).map((x:string,j:number)=><button disabled={done} className={answers[i]===j?'picked':''} key={j} onClick={()=>setAnswers(a=>({...a,[i]:j}))}>{x}</button>)}</div>{done&&<p className={answers[i]===q.answerIndex?'correct':'wrong'}>{answers[i]===q.answerIndex?'✓ صحيح':`✗ الصحيح: ${q.choices?.[q.answerIndex]}`} — {q.explanation}</p>}<small>{q.sourceRef}</small></article>)}{!done?<button className="primary wide" onClick={()=>finish(false)}>سلّم الامتحان</button>:<div className="exam-result"><b>{score}/{questions.length}</b><h3>{pct}%</h3><p>{pct>=80?'ممتاز — هسه اشتغل على الأخطاء القليلة.':pct>=60?'ناجح لكن بعد عندك ثقوب واضحة.':'النتيجة مو مطمئنة؛ Rescue Mode هو الخطوة التالية.'}</p><button className="ghost" onClick={start}><RotateCcw/> امتحان جديد</button></div>}</div>}</div>
}

export function VoiceTutor({state,notify}:Props){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const [question,setQuestion]=useState('');const [answer,setAnswer]=useState<any>(null);const [busy,setBusy]=useState('');const [recording,setRecording]=useState(false);const rec=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);const mats=readyFor(state,courseId);
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 async function startRecord(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;chunks.current=[];const r=new MediaRecorder(s);rec.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});s.getTracks().forEach(t=>t.stop());stream.current=null;setBusy('speech');try{const t:any=await speechToText(blob);setQuestion(String(t.text||''));notify('حوّلت سؤالك الصوتي إلى نص محليًا')}catch(e){notify((e as Error).message)}finally{setBusy('')}};r.start(500);setRecording(true)}catch(e){notify((e as Error).message)}}
 function stopRecord(){rec.current?.stop();setRecording(false)}
 async function ask(){if(!question.trim()||!mats.length)return;setBusy('ask');try{const hits=retrieve(mats,question,10);const context=hits.map(h=>`SOURCE ${h.material}\n[[PAGE ${h.page}]]\n${h.text}`).join('\n\n');const r:any=await aiTask('chat',{context,question});setAnswer(r)}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 return <div className="voice-layout"><div className="panel"><div className="section-head"><div><span className="eyebrow">VOICE TUTOR</span><h3>اسأل بصوتك، والجواب من مادتك</h3><p>التسجيل → Whisper محلي → Course Brain → جواب قابل للقراءة بصوت.</p></div><Mic/></div><select value={courseId} onChange={e=>{setCourseId(e.target.value);setAnswer(null)}}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea rows={5} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="اكتب سؤالك أو سجله بالصوت…"/><div className="voice-actions">{recording?<button className="danger" onClick={stopRecord}><Square/> إيقاف التسجيل</button>:<button className="ghost" onClick={startRecord} disabled={!!busy}><Mic/> سجل سؤال</button>}<button className="primary" onClick={ask} disabled={!!busy||!question.trim()||!mats.length}>{busy?<LoaderCircle className="spin"/>:<Brain/>} اسأل المدرس</button></div></div>{answer&&<div className="panel voice-answer"><div className="section-head"><h3>جواب Scholar</h3><button className="ghost compact" onClick={()=>textToSpeech(String(answer.text||''))}><Volume2/> اقرأه</button></div><p>{answer.text}</p><div className="source-chips">{(answer.sourceRefs||[]).map((x:string,i:number)=><span key={i}>{x}</span>)}</div></div>}</div>
}

export function LearningGraph({state}:Pick<Props,'state'>){
 const [courseId,setCourseId]=useState(state.courses[0]?.id||'');const course=state.courses.find(c=>c.id===courseId);const topics=state.topics.filter(t=>t.courseId===courseId).slice().sort((a,b)=>a.mastery-b.mastery);const weak=weakest(state,courseId);const cards=state.flashcards.filter(c=>c.courseId===courseId);const artifacts=state.artifacts.filter(a=>a.courseId===courseId);
 const stats=useMemo(()=>({mastery:course?courseMastery(state,course.id):0,tested:topics.filter(t=>t.attempts>0).length,due:cards.filter(c=>new Date(c.dueAt)<=new Date()).length,outputs:artifacts.length}),[state,courseId]);
 return <div className="tool-stack"><div className="panel"><div className="section-head"><div><span className="eyebrow">STUDENT LEARNING GRAPH</span><h3>خريطة تعلمك، مو مجرد قائمة ملفات</h3><p>كل اختبار ومراجعة يغير وزن المفهوم ويقرر شنو يطلع لك بعدين.</p></div><GitBranch/></div><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{state.courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="graph-metrics"><div><b>{stats.mastery}%</b><small>إتقان المادة</small></div><div><b>{stats.tested}</b><small>مفاهيم مختبرة</small></div><div><b>{stats.due}</b><small>مراجعات مستحقة</small></div><div><b>{stats.outputs}</b><small>مخرجات أكاديمية</small></div></div></div><div className="learning-network">{topics.length?topics.map((t,i)=><div className={`learning-node ${t.mastery<45?'critical':t.mastery<70?'learning':'strong'}`} key={t.id}><span>{i+1}</span><div><b>{t.title}</b><small>{t.sourceRef||'من مصادر المادة'} • {t.attempts} محاولة</small><div className="node-bar"><i style={{width:`${t.mastery}%`}}/></div></div><em>{t.mastery}%</em></div>):<div className="panel graph-empty"><BookOpen/><h3>الخريطة بعد ما عندها بيانات</h3><p>شغّل اختبار أو بطاقات حتى يبدأ ScholarMCP يبني علاقته الحقيقية بمستواك.</p></div>}</div>{weak.length>0&&<div className="panel"><h4>أضعف ثلاث عقد حاليًا</h4>{weak.map(x=><p key={x.id}>• {x.title} — {x.mastery}%</p>)}</div>}</div>
}
